BEGIN;

INSERT INTO public.products (
  id,
  name,
  slug,
  product_type,
  character_id,
  character_name,
  category,
  collection_ids,
  short_description,
  description,
  tags,
  status,
  is_trending,
  is_featured,
  media_asset_id,
  media,
  thumbnail_mode,
  watermark_mode,
  preview_quality,
  pricing,
  offer,
  performance,
  creator_activity,
  campaign,
  availability,
  duration,
  resolution,
  format,
  access,
  licenses,
  pdp_value_cards,
  file_details,
  sales,
  revenue_inr,
  prompt_data,
  caption_pack_data,
  ai_image_data,
  bundle_data,
  created_at,
  updated_at
)
VALUES
  (
    'dummy-video-01',
    'Midnight Footwork',
    'dummy-midnight-footwork',
    'VIDEO',
    NULL,
    'Milo',
    'Hip Hop',
    '{}',
    'Low-light isolations with a late drop made for night-drive reels.',
    'Crisp footwork under cool street lighting. Timed for a delayed drop that rewards viewers who stay past the first three seconds.',
    ARRAY['hip-hop', 'footwork', 'night']::text[],
    'active',
    TRUE,
    TRUE,
    NULL,
    '{"thumbnail":"/media/videos/pulse-drop.jpg","previewVideo":"/media/videos/pulse-drop.jpg","downloadFileName":"dummy-midnight-footwork-1080.mp4","downloadFileSize":"11.6 MB"}'::jsonb,
    'frame',
    'global',
    'high',
    '{"INR":{"regularPrice":999,"currentPrice":799},"USD":{"regularPrice":12.99,"currentPrice":9.99}}'::jsonb,
    '{"enabled":true,"label":"LAUNCH PRICE ACTIVE","startDate":"2026-09-01T00:00:00.000Z","endDate":"2026-10-31T23:59:59.000Z"}'::jsonb,
    '{"mode":"demo","plays":"1.8M","playsNumeric":1800000,"likes":"142K","likesNumeric":142000,"shares":"29K","sharesNumeric":29000,"engagementPct":9.1,"status":"trending","badge":"TRENDING NOW","insight":"Strong retention through the delayed drop.","metricLabel":"PLAYS","engagementText":"142K likes · 29K shares","supportingText":"Creators are posting this format right now.","momentumLabel":"MOMENTUM IS CLIMBING ↑"}'::jsonb,
    '{"mode":"demo","addedThisWeek":76,"saved":486,"last24h":14,"activityLevel":"high","note":"Dummy catalog video for UI review."}'::jsonb,
    '{"enabled":true,"label":"TRENDING NOW","headline":"Low-light isolations with a late drop made for night-drive reels.","supportingText":"Crisp footwork under cool street lighting. Timed for a delayed drop that rewards viewers w","ctaText":"Get Midnight Footwork","microMessages":["Dummy seed","UI review","Hip Hop"]}'::jsonb,
    '{"mode":"unlimited"}'::jsonb,
    '0:17',
    '1080x1920',
    'MP4',
    'Instant access',
    '[{"id":"lic-personal","name":"Personal","description":"Social posts & personal projects","priceAdjustment":0},{"id":"lic-commercial","name":"Commercial","description":"Brand & client work","priceAdjustment":20}]'::jsonb,
    '[{"badge":"VIDEO INCLUDED","title":"Full vertical master file","description":"1080×1920 MP4 ready for Reels, Shorts, and TikTok."},{"badge":"INSTANT ACCESS","title":"Download after checkout","description":"No rendering queue — your file unlocks immediately."},{"badge":"POST-READY","title":"Built for feed retention","description":"Timed for hooks, drops, and replay loops."}]'::jsonb,
    '{"dimensionsSupporting":"Full HD vertical video","formatSupporting":"Ready-to-post MP4","accessSupporting":"Download after checkout","usageMain":"Personal + social","usageSupporting":"Use it in your own content"}'::jsonb,
    286,
    228514,
    NULL,
    NULL,
    NULL,
    NULL,
    '2026-09-13T10:00:00.000Z'::timestamptz,
    '2026-09-13T10:00:00.000Z'::timestamptz
  ),
  (
    'dummy-video-02',
    'Saffron Spin-Out',
    'dummy-saffron-spin-out',
    'VIDEO',
    NULL,
    'Zara',
    'Bollywood',
    '{}',
    'Festival-bright turns with a clean camera orbit finish.',
    'Warm saffron wardrobe tones and expressive spins. Built for festive calendar posts and brand collabs that need cultural energy without clutter.',
    ARRAY['bollywood', 'spin', 'festive']::text[],
    'active',
    TRUE,
    FALSE,
    NULL,
    '{"thumbnail":"/media/videos/saffron-swing.jpg","previewVideo":"/media/videos/saffron-swing.jpg","downloadFileName":"dummy-saffron-spin-out-1080.mp4","downloadFileSize":"11.6 MB"}'::jsonb,
    'frame',
    'global',
    'high',
    '{"INR":{"regularPrice":1199,"currentPrice":999},"USD":{"regularPrice":14.99,"currentPrice":11.99}}'::jsonb,
    '{"enabled":true,"label":"LAUNCH PRICE ACTIVE","startDate":"2026-09-01T00:00:00.000Z","endDate":"2026-10-31T23:59:59.000Z"}'::jsonb,
    '{"mode":"demo","plays":"960K","playsNumeric":960000,"likes":"88K","likesNumeric":88000,"shares":"17K","sharesNumeric":17000,"engagementPct":10.4,"status":"high-engagement","badge":"FESTIVE HIT","insight":"Shares spike on weekend evenings.","metricLabel":"PLAYS","engagementText":"88K likes · 17K shares","supportingText":"Creators are posting this format right now.","momentumLabel":"MOMENTUM IS CLIMBING ↑"}'::jsonb,
    '{"mode":"demo","addedThisWeek":88,"saved":398,"last24h":26,"activityLevel":"high","note":"Dummy catalog video for UI review."}'::jsonb,
    '{"enabled":true,"label":"FESTIVE HIT","headline":"Festival-bright turns with a clean camera orbit finish.","supportingText":"Warm saffron wardrobe tones and expressive spins. Built for festive calendar posts and bra","ctaText":"Get Saffron Spin-Out","microMessages":["Dummy seed","UI review","Bollywood"]}'::jsonb,
    '{"mode":"unlimited"}'::jsonb,
    '0:21',
    '1080x1920',
    'MP4',
    'Instant access',
    '[{"id":"lic-personal","name":"Personal","description":"Social posts & personal projects","priceAdjustment":0},{"id":"lic-commercial","name":"Commercial","description":"Brand & client work","priceAdjustment":15}]'::jsonb,
    '[{"badge":"VIDEO INCLUDED","title":"Full vertical master file","description":"1080×1920 MP4 ready for Reels, Shorts, and TikTok."},{"badge":"INSTANT ACCESS","title":"Download after checkout","description":"No rendering queue — your file unlocks immediately."},{"badge":"POST-READY","title":"Built for feed retention","description":"Timed for hooks, drops, and replay loops."}]'::jsonb,
    '{"dimensionsSupporting":"Full HD vertical video","formatSupporting":"Ready-to-post MP4","accessSupporting":"Download after checkout","usageMain":"Personal + social","usageSupporting":"Use it in your own content"}'::jsonb,
    198,
    197802,
    NULL,
    NULL,
    NULL,
    NULL,
    '2026-09-13T10:00:00.000Z'::timestamptz,
    '2026-09-13T10:00:00.000Z'::timestamptz
  ),
  (
    'dummy-video-03',
    'Quiet Flex Loop',
    'dummy-quiet-flex-loop',
    'VIDEO',
    NULL,
    'Kai',
    'Chill',
    '{}',
    'Soft swagger loop that never feels forced.',
    'Minimal movement, maximum attitude. A seamless loop for aesthetic accounts that want confidence without chaos.',
    ARRAY['chill', 'loop', 'aesthetic']::text[],
    'active',
    FALSE,
    FALSE,
    NULL,
    '{"thumbnail":"/media/videos/quiet-flex.jpg","previewVideo":"/media/videos/quiet-flex.jpg","downloadFileName":"dummy-quiet-flex-loop-1080.mp4","downloadFileSize":"11.6 MB"}'::jsonb,
    'frame',
    'global',
    'high',
    '{"INR":{"regularPrice":799,"currentPrice":799},"USD":{"regularPrice":9.99,"currentPrice":9.99}}'::jsonb,
    '{"enabled":false,"label":""}'::jsonb,
    '{"mode":"demo","plays":"410K","playsNumeric":410000,"likes":"36K","likesNumeric":36000,"shares":"6.1K","sharesNumeric":6100,"engagementPct":7.4,"status":"normal","badge":"STEADY","insight":"Reliable mid-funnel performer.","metricLabel":"PLAYS","engagementText":"36K likes · 6.1K shares","supportingText":"Creators are posting this format right now.","momentumLabel":"MOMENTUM IS CLIMBING ↑"}'::jsonb,
    '{"mode":"demo","addedThisWeek":84,"saved":344,"last24h":12,"activityLevel":"normal","note":"Dummy catalog video for UI review."}'::jsonb,
    '{"enabled":true,"label":"STEADY","headline":"Soft swagger loop that never feels forced.","supportingText":"Minimal movement, maximum attitude. A seamless loop for aesthetic accounts that want confi","ctaText":"Get Quiet Flex Loop","microMessages":["Dummy seed","UI review","Chill"]}'::jsonb,
    '{"mode":"unlimited"}'::jsonb,
    '0:12',
    '1080x1920',
    'MP4',
    'Instant access',
    '[{"id":"lic-personal","name":"Personal","description":"Social posts & personal projects","priceAdjustment":0},{"id":"lic-commercial","name":"Commercial","description":"Brand & client work","priceAdjustment":15}]'::jsonb,
    '[{"badge":"VIDEO INCLUDED","title":"Full vertical master file","description":"1080×1920 MP4 ready for Reels, Shorts, and TikTok."},{"badge":"INSTANT ACCESS","title":"Download after checkout","description":"No rendering queue — your file unlocks immediately."},{"badge":"POST-READY","title":"Built for feed retention","description":"Timed for hooks, drops, and replay loops."}]'::jsonb,
    '{"dimensionsSupporting":"Full HD vertical video","formatSupporting":"Ready-to-post MP4","accessSupporting":"Download after checkout","usageMain":"Personal + social","usageSupporting":"Use it in your own content"}'::jsonb,
    144,
    114956,
    NULL,
    NULL,
    NULL,
    NULL,
    '2026-09-13T10:00:00.000Z'::timestamptz,
    '2026-09-13T10:00:00.000Z'::timestamptz
  ),
  (
    'dummy-video-04',
    'Glitch Party Cut',
    'dummy-glitch-party-cut',
    'VIDEO',
    NULL,
    'Rio',
    'Viral Moves',
    '{}',
    'Strobe-timed cuts that feel like a party edit.',
    'Hard cuts and playful glitch accents. Designed for creators who need a high-energy open that still reads on mute.',
    ARRAY['viral', 'glitch', 'party']::text[],
    'active',
    TRUE,
    TRUE,
    NULL,
    '{"thumbnail":"/media/videos/glitch-party.jpg","previewVideo":"/media/videos/glitch-party.jpg","downloadFileName":"dummy-glitch-party-cut-1080.mp4","downloadFileSize":"11.6 MB"}'::jsonb,
    'frame',
    'global',
    'high',
    '{"INR":{"regularPrice":1099,"currentPrice":849},"USD":{"regularPrice":13.99,"currentPrice":10.49}}'::jsonb,
    '{"enabled":true,"label":"LAUNCH PRICE ACTIVE","startDate":"2026-09-01T00:00:00.000Z","endDate":"2026-10-31T23:59:59.000Z"}'::jsonb,
    '{"mode":"demo","plays":"2.4M","playsNumeric":2400000,"likes":"201K","likesNumeric":201000,"shares":"51K","sharesNumeric":51000,"engagementPct":11.8,"status":"viral","badge":"VIRAL","insight":"Top share rate in the party niche.","metricLabel":"PLAYS","engagementText":"201K likes · 51K shares","supportingText":"Creators are posting this format right now.","momentumLabel":"MOMENTUM IS CLIMBING ↑"}'::jsonb,
    '{"mode":"demo","addedThisWeek":61,"saved":521,"last24h":9,"activityLevel":"high","note":"Dummy catalog video for UI review."}'::jsonb,
    '{"enabled":true,"label":"VIRAL","headline":"Strobe-timed cuts that feel like a party edit.","supportingText":"Hard cuts and playful glitch accents. Designed for creators who need a high-energy open th","ctaText":"Get Glitch Party Cut","microMessages":["Dummy seed","UI review","Viral Moves"]}'::jsonb,
    '{"mode":"unlimited"}'::jsonb,
    '0:15',
    '1080x1920',
    'MP4',
    'Instant access',
    '[{"id":"lic-personal","name":"Personal","description":"Social posts & personal projects","priceAdjustment":0},{"id":"lic-commercial","name":"Commercial","description":"Brand & client work","priceAdjustment":20}]'::jsonb,
    '[{"badge":"VIDEO INCLUDED","title":"Full vertical master file","description":"1080×1920 MP4 ready for Reels, Shorts, and TikTok."},{"badge":"INSTANT ACCESS","title":"Download after checkout","description":"No rendering queue — your file unlocks immediately."},{"badge":"POST-READY","title":"Built for feed retention","description":"Timed for hooks, drops, and replay loops."}]'::jsonb,
    '{"dimensionsSupporting":"Full HD vertical video","formatSupporting":"Ready-to-post MP4","accessSupporting":"Download after checkout","usageMain":"Personal + social","usageSupporting":"Use it in your own content"}'::jsonb,
    321,
    272529,
    NULL,
    NULL,
    NULL,
    NULL,
    '2026-09-13T10:00:00.000Z'::timestamptz,
    '2026-09-13T10:00:00.000Z'::timestamptz
  ),
  (
    'dummy-video-05',
    'Orbit Hop Duo',
    'dummy-orbit-hop-duo',
    'VIDEO',
    NULL,
    'Nia',
    'Cute & Fun',
    '{}',
    'Bounce-hop choreography with playful camera orbits.',
    'Light, friendly energy with hop accents. Ideal for duo or reaction formats where personality matters as much as the move.',
    ARRAY['cute', 'duo', 'hop']::text[],
    'active',
    FALSE,
    TRUE,
    NULL,
    '{"thumbnail":"/media/videos/orbit-hop.jpg","previewVideo":"/media/videos/orbit-hop.jpg","downloadFileName":"dummy-orbit-hop-duo-1080.mp4","downloadFileSize":"11.6 MB"}'::jsonb,
    'frame',
    'global',
    'high',
    '{"INR":{"regularPrice":899,"currentPrice":749},"USD":{"regularPrice":11.99,"currentPrice":8.99}}'::jsonb,
    '{"enabled":true,"label":"LAUNCH PRICE ACTIVE","startDate":"2026-09-01T00:00:00.000Z","endDate":"2026-10-31T23:59:59.000Z"}'::jsonb,
    '{"mode":"demo","plays":"720K","playsNumeric":720000,"likes":"61K","likesNumeric":61000,"shares":"12K","sharesNumeric":12000,"engagementPct":8.6,"status":"high-engagement","badge":"CREATOR FAVE","insight":"Saves climb when posted with a caption pack.","metricLabel":"PLAYS","engagementText":"61K likes · 12K shares","supportingText":"Creators are posting this format right now.","momentumLabel":"MOMENTUM IS CLIMBING ↑"}'::jsonb,
    '{"mode":"demo","addedThisWeek":57,"saved":367,"last24h":15,"activityLevel":"normal","note":"Dummy catalog video for UI review."}'::jsonb,
    '{"enabled":true,"label":"CREATOR FAVE","headline":"Bounce-hop choreography with playful camera orbits.","supportingText":"Light, friendly energy with hop accents. Ideal for duo or reaction formats where personali","ctaText":"Get Orbit Hop Duo","microMessages":["Dummy seed","UI review","Cute & Fun"]}'::jsonb,
    '{"mode":"unlimited"}'::jsonb,
    '0:19',
    '1080x1920',
    'MP4',
    'Instant access',
    '[{"id":"lic-personal","name":"Personal","description":"Social posts & personal projects","priceAdjustment":0},{"id":"lic-commercial","name":"Commercial","description":"Brand & client work","priceAdjustment":20}]'::jsonb,
    '[{"badge":"VIDEO INCLUDED","title":"Full vertical master file","description":"1080×1920 MP4 ready for Reels, Shorts, and TikTok."},{"badge":"INSTANT ACCESS","title":"Download after checkout","description":"No rendering queue — your file unlocks immediately."},{"badge":"POST-READY","title":"Built for feed retention","description":"Timed for hooks, drops, and replay loops."}]'::jsonb,
    '{"dimensionsSupporting":"Full HD vertical video","formatSupporting":"Ready-to-post MP4","accessSupporting":"Download after checkout","usageMain":"Personal + social","usageSupporting":"Use it in your own content"}'::jsonb,
    167,
    125083,
    NULL,
    NULL,
    NULL,
    NULL,
    '2026-09-13T10:00:00.000Z'::timestamptz,
    '2026-09-13T10:00:00.000Z'::timestamptz
  ),
  (
    'dummy-video-06',
    'Velvet Turn Editorial',
    'dummy-velvet-turn-editorial',
    'VIDEO',
    NULL,
    'Zara',
    'Editorial',
    '{}',
    'Premium turn sequence with fashion-film pacing.',
    'Slower editorial timing and velvet lighting. Made for brand lookbooks and polished creator portfolios.',
    ARRAY['editorial', 'premium', 'turn']::text[],
    'active',
    FALSE,
    FALSE,
    NULL,
    '{"thumbnail":"/media/videos/velvet-turn.jpg","previewVideo":"/media/videos/velvet-turn.jpg","downloadFileName":"dummy-velvet-turn-editorial-1080.mp4","downloadFileSize":"11.6 MB"}'::jsonb,
    'frame',
    'global',
    'high',
    '{"INR":{"regularPrice":1499,"currentPrice":1299},"USD":{"regularPrice":17.99,"currentPrice":14.99}}'::jsonb,
    '{"enabled":true,"label":"LAUNCH PRICE ACTIVE","startDate":"2026-09-01T00:00:00.000Z","endDate":"2026-10-31T23:59:59.000Z"}'::jsonb,
    '{"mode":"demo","plays":"280K","playsNumeric":280000,"likes":"29K","likesNumeric":29000,"shares":"4.8K","sharesNumeric":4800,"engagementPct":9,"status":"normal","badge":"PREMIUM","insight":"Higher convert among brand buyers.","metricLabel":"PLAYS","engagementText":"29K likes · 4.8K shares","supportingText":"Creators are posting this format right now.","momentumLabel":"MOMENTUM IS CLIMBING ↑"}'::jsonb,
    '{"mode":"demo","addedThisWeek":82,"saved":292,"last24h":20,"activityLevel":"normal","note":"Dummy catalog video for UI review."}'::jsonb,
    '{"enabled":true,"label":"PREMIUM","headline":"Premium turn sequence with fashion-film pacing.","supportingText":"Slower editorial timing and velvet lighting. Made for brand lookbooks and polished creator","ctaText":"Get Velvet Turn Editorial","microMessages":["Dummy seed","UI review","Editorial"]}'::jsonb,
    '{"mode":"unlimited"}'::jsonb,
    '0:24',
    '1080x1920',
    'MP4',
    'Instant access',
    '[{"id":"lic-personal","name":"Personal","description":"Social posts & personal projects","priceAdjustment":0},{"id":"lic-commercial","name":"Commercial","description":"Brand & client work","priceAdjustment":15}]'::jsonb,
    '[{"badge":"VIDEO INCLUDED","title":"Full vertical master file","description":"1080×1920 MP4 ready for Reels, Shorts, and TikTok."},{"badge":"INSTANT ACCESS","title":"Download after checkout","description":"No rendering queue — your file unlocks immediately."},{"badge":"POST-READY","title":"Built for feed retention","description":"Timed for hooks, drops, and replay loops."}]'::jsonb,
    '{"dimensionsSupporting":"Full HD vertical video","formatSupporting":"Ready-to-post MP4","accessSupporting":"Download after checkout","usageMain":"Personal + social","usageSupporting":"Use it in your own content"}'::jsonb,
    92,
    119508,
    NULL,
    NULL,
    NULL,
    NULL,
    '2026-09-13T10:00:00.000Z'::timestamptz,
    '2026-09-13T10:00:00.000Z'::timestamptz
  ),
  (
    'dummy-image-01',
    'Pastel Studio Portrait',
    'dummy-pastel-studio-portrait',
    'AI_IMAGE',
    NULL,
    NULL,
    'Portrait',
    '{}',
    'Soft pastel portrait with clean studio light.',
    'A single high-res character still with gentle color and crisp edges — ideal as a profile hero or prompt companion.',
    ARRAY['portrait', 'pastel', 'studio']::text[],
    'active',
    TRUE,
    TRUE,
    NULL,
    '{"thumbnail":"/media/categories/cute-fun.jpg"}'::jsonb,
    'custom',
    'global',
    'optimized',
    '{"INR":{"regularPrice":999,"currentPrice":799},"USD":{"regularPrice":12.99,"currentPrice":9.99}}'::jsonb,
    '{"enabled":true,"label":"LIMITED INTRO PRICE","startDate":"2026-09-01T00:00:00.000Z","endDate":"2026-10-20T23:59:59.000Z"}'::jsonb,
    '{"mode":"demo","plays":"184800","playsNumeric":184800,"likes":"62K","likesNumeric":61600,"shares":"12K","sharesNumeric":12320,"engagementPct":8.2,"status":"trending","badge":"IMAGE","insight":"Dummy AI image for storefront card review.","metricLabel":"VIEWS","engagementText":"62K likes · 12K shares","supportingText":"Creators are posting this format right now.","momentumLabel":"MOMENTUM IS CLIMBING ↑"}'::jsonb,
    '{"mode":"demo","addedThisWeek":18,"saved":214,"last24h":5,"activityLevel":"normal","note":"Dummy AI image seed."}'::jsonb,
    '{"enabled":true,"label":"LIMITED INTRO PRICE","headline":"Soft pastel portrait with clean studio light.","supportingText":"","ctaText":"Get this image","microMessages":["Dummy seed"]}'::jsonb,
    '{"mode":"unlimited"}'::jsonb,
    '',
    '2048x2048',
    'PNG',
    'Instant access',
    '[{"id":"lic-personal","name":"Personal","description":"Social posts & personal projects","priceAdjustment":0},{"id":"lic-commercial","name":"Commercial","description":"Brand & client work","priceAdjustment":18}]'::jsonb,
    '[{"badge":"HIGH-RES PNG","title":"Print and post ready","description":"2048×2048 PNG with clean edges for social crops."},{"badge":"COMMERCIAL-SAFE","title":"Clear licensing tiers","description":"Personal and commercial options at checkout."},{"badge":"CHARACTER-READY","title":"Consistent look language","description":"Designed to pair with prompts and caption packs."}]'::jsonb,
    '{"dimensionsSupporting":"Square / vertical friendly","formatSupporting":"PNG or text unlock","accessSupporting":"Instant library access","usageMain":"Personal + social","usageSupporting":"Commercial upgrade available"}'::jsonb,
    154,
    123046,
    NULL,
    NULL,
    '{"resolution":"2048x2048","format":"PNG","fileSizeLabel":"2.4 MB","images":[{"id":"dummy-image-01-1","url":"/media/categories/cute-fun.jpg","previewUrl":"/media/categories/cute-fun.jpg","fileName":"dummy-image-01-1.png","isCover":true,"sizeLabel":"2.4 MB"}],"introTimerDays":14,"introTimerExtensionHours":4}'::jsonb,
    NULL,
    '2026-09-13T10:00:00.000Z'::timestamptz,
    '2026-09-13T10:00:00.000Z'::timestamptz
  ),
  (
    'dummy-image-02',
    'Neon Alley Character',
    'dummy-neon-alley-character',
    'AI_IMAGE',
    NULL,
    NULL,
    'Street',
    '{}',
    'Night-street character with neon rim light.',
    'Moody alley lighting and bold silhouette. Built for cyber-pop feeds and music promo art.',
    ARRAY['neon', 'street', 'night']::text[],
    'active',
    TRUE,
    FALSE,
    NULL,
    '{"thumbnail":"/media/videos/neon-shuffle.jpg"}'::jsonb,
    'custom',
    'global',
    'optimized',
    '{"INR":{"regularPrice":999,"currentPrice":849},"USD":{"regularPrice":12.99,"currentPrice":10.49}}'::jsonb,
    '{"enabled":true,"label":"LIMITED INTRO PRICE","startDate":"2026-09-01T00:00:00.000Z","endDate":"2026-10-20T23:59:59.000Z"}'::jsonb,
    '{"mode":"demo","plays":"145200","playsNumeric":145200,"likes":"48K","likesNumeric":48400,"shares":"10K","sharesNumeric":9680,"engagementPct":8.2,"status":"trending","badge":"IMAGE","insight":"Dummy AI image for storefront card review.","metricLabel":"VIEWS","engagementText":"48K likes · 10K shares","supportingText":"Creators are posting this format right now.","momentumLabel":"MOMENTUM IS CLIMBING ↑"}'::jsonb,
    '{"mode":"demo","addedThisWeek":18,"saved":181,"last24h":5,"activityLevel":"normal","note":"Dummy AI image seed."}'::jsonb,
    '{"enabled":true,"label":"LIMITED INTRO PRICE","headline":"Night-street character with neon rim light.","supportingText":"","ctaText":"Get this image","microMessages":["Dummy seed"]}'::jsonb,
    '{"mode":"unlimited"}'::jsonb,
    '',
    '2048x2048',
    'PNG',
    'Instant access',
    '[{"id":"lic-personal","name":"Personal","description":"Social posts & personal projects","priceAdjustment":0},{"id":"lic-commercial","name":"Commercial","description":"Brand & client work","priceAdjustment":18}]'::jsonb,
    '[{"badge":"HIGH-RES PNG","title":"Print and post ready","description":"2048×2048 PNG with clean edges for social crops."},{"badge":"COMMERCIAL-SAFE","title":"Clear licensing tiers","description":"Personal and commercial options at checkout."},{"badge":"CHARACTER-READY","title":"Consistent look language","description":"Designed to pair with prompts and caption packs."}]'::jsonb,
    '{"dimensionsSupporting":"Square / vertical friendly","formatSupporting":"PNG or text unlock","accessSupporting":"Instant library access","usageMain":"Personal + social","usageSupporting":"Commercial upgrade available"}'::jsonb,
    121,
    102729,
    NULL,
    NULL,
    '{"resolution":"2048x2048","format":"PNG","fileSizeLabel":"2.4 MB","images":[{"id":"dummy-image-02-1","url":"/media/videos/neon-shuffle.jpg","previewUrl":"/media/videos/neon-shuffle.jpg","fileName":"dummy-image-02-1.png","isCover":true,"sizeLabel":"2.4 MB"}],"introTimerDays":14,"introTimerExtensionHours":4}'::jsonb,
    NULL,
    '2026-09-13T10:00:00.000Z'::timestamptz,
    '2026-09-13T10:00:00.000Z'::timestamptz
  ),
  (
    'dummy-image-03',
    'Mango Mascot Still',
    'dummy-mango-mascot-still',
    'AI_IMAGE',
    NULL,
    NULL,
    'Mascot',
    '{}',
    'Cheerful mango mascot on a clean backdrop.',
    'Product-friendly mascot art with readable shapes at phone size. Great for stickers, shorts thumbnails, and merch mockups.',
    ARRAY['mascot', 'food', 'cute']::text[],
    'active',
    FALSE,
    TRUE,
    NULL,
    '{"thumbnail":"/media/videos/mango-pop.jpg"}'::jsonb,
    'custom',
    'global',
    'optimized',
    '{"INR":{"regularPrice":899,"currentPrice":699},"USD":{"regularPrice":10.99,"currentPrice":8.49}}'::jsonb,
    '{"enabled":true,"label":"LIMITED INTRO PRICE","startDate":"2026-09-01T00:00:00.000Z","endDate":"2026-10-20T23:59:59.000Z"}'::jsonb,
    '{"mode":"demo","plays":"249600","playsNumeric":249600,"likes":"83K","likesNumeric":83200,"shares":"17K","sharesNumeric":16640,"engagementPct":8.2,"status":"normal","badge":"IMAGE","insight":"Dummy AI image for storefront card review.","metricLabel":"VIEWS","engagementText":"83K likes · 17K shares","supportingText":"Creators are posting this format right now.","momentumLabel":"MOMENTUM IS CLIMBING ↑"}'::jsonb,
    '{"mode":"demo","addedThisWeek":18,"saved":268,"last24h":5,"activityLevel":"normal","note":"Dummy AI image seed."}'::jsonb,
    '{"enabled":true,"label":"LIMITED INTRO PRICE","headline":"Cheerful mango mascot on a clean backdrop.","supportingText":"","ctaText":"Get this image","microMessages":["Dummy seed"]}'::jsonb,
    '{"mode":"unlimited"}'::jsonb,
    '',
    '2048x2048',
    'PNG',
    'Instant access',
    '[{"id":"lic-personal","name":"Personal","description":"Social posts & personal projects","priceAdjustment":0},{"id":"lic-commercial","name":"Commercial","description":"Brand & client work","priceAdjustment":18}]'::jsonb,
    '[{"badge":"HIGH-RES PNG","title":"Print and post ready","description":"2048×2048 PNG with clean edges for social crops."},{"badge":"COMMERCIAL-SAFE","title":"Clear licensing tiers","description":"Personal and commercial options at checkout."},{"badge":"CHARACTER-READY","title":"Consistent look language","description":"Designed to pair with prompts and caption packs."}]'::jsonb,
    '{"dimensionsSupporting":"Square / vertical friendly","formatSupporting":"PNG or text unlock","accessSupporting":"Instant library access","usageMain":"Personal + social","usageSupporting":"Commercial upgrade available"}'::jsonb,
    208,
    145392,
    NULL,
    NULL,
    '{"resolution":"2048x2048","format":"PNG","fileSizeLabel":"2.4 MB","images":[{"id":"dummy-image-03-1","url":"/media/videos/mango-pop.jpg","previewUrl":"/media/videos/mango-pop.jpg","fileName":"dummy-image-03-1.png","isCover":true,"sizeLabel":"2.4 MB"}],"introTimerDays":14,"introTimerExtensionHours":4}'::jsonb,
    NULL,
    '2026-09-13T10:00:00.000Z'::timestamptz,
    '2026-09-13T10:00:00.000Z'::timestamptz
  ),
  (
    'dummy-image-04',
    'Festival Lookbook Frame',
    'dummy-festival-lookbook-frame',
    'AI_IMAGE',
    NULL,
    NULL,
    'Fashion',
    '{}',
    'Editorial festival fashion frame with warm glow.',
    'Soft bokeh and detailed fabric folds. Use as a lookbook plate or fashion prompt reference.',
    ARRAY['fashion', 'festival', 'editorial']::text[],
    'active',
    FALSE,
    FALSE,
    NULL,
    '{"thumbnail":"/media/categories/bollywood.jpg"}'::jsonb,
    'custom',
    'global',
    'optimized',
    '{"INR":{"regularPrice":1099,"currentPrice":899},"USD":{"regularPrice":13.99,"currentPrice":10.99}}'::jsonb,
    '{"enabled":true,"label":"LIMITED INTRO PRICE","startDate":"2026-09-01T00:00:00.000Z","endDate":"2026-10-20T23:59:59.000Z"}'::jsonb,
    '{"mode":"demo","plays":"116400","playsNumeric":116400,"likes":"39K","likesNumeric":38800,"shares":"8K","sharesNumeric":7760,"engagementPct":8.2,"status":"normal","badge":"IMAGE","insight":"Dummy AI image for storefront card review.","metricLabel":"VIEWS","engagementText":"39K likes · 8K shares","supportingText":"Creators are posting this format right now.","momentumLabel":"MOMENTUM IS CLIMBING ↑"}'::jsonb,
    '{"mode":"demo","addedThisWeek":18,"saved":157,"last24h":5,"activityLevel":"normal","note":"Dummy AI image seed."}'::jsonb,
    '{"enabled":true,"label":"LIMITED INTRO PRICE","headline":"Editorial festival fashion frame with warm glow.","supportingText":"","ctaText":"Get this image","microMessages":["Dummy seed"]}'::jsonb,
    '{"mode":"unlimited"}'::jsonb,
    '',
    '2048x2048',
    'PNG',
    'Instant access',
    '[{"id":"lic-personal","name":"Personal","description":"Social posts & personal projects","priceAdjustment":0},{"id":"lic-commercial","name":"Commercial","description":"Brand & client work","priceAdjustment":18}]'::jsonb,
    '[{"badge":"HIGH-RES PNG","title":"Print and post ready","description":"2048×2048 PNG with clean edges for social crops."},{"badge":"COMMERCIAL-SAFE","title":"Clear licensing tiers","description":"Personal and commercial options at checkout."},{"badge":"CHARACTER-READY","title":"Consistent look language","description":"Designed to pair with prompts and caption packs."}]'::jsonb,
    '{"dimensionsSupporting":"Square / vertical friendly","formatSupporting":"PNG or text unlock","accessSupporting":"Instant library access","usageMain":"Personal + social","usageSupporting":"Commercial upgrade available"}'::jsonb,
    97,
    87203,
    NULL,
    NULL,
    '{"resolution":"2048x2048","format":"PNG","fileSizeLabel":"2.4 MB","images":[{"id":"dummy-image-04-1","url":"/media/categories/bollywood.jpg","previewUrl":"/media/categories/bollywood.jpg","fileName":"dummy-image-04-1.png","isCover":true,"sizeLabel":"2.4 MB"}],"introTimerDays":14,"introTimerExtensionHours":4}'::jsonb,
    NULL,
    '2026-09-13T10:00:00.000Z'::timestamptz,
    '2026-09-13T10:00:00.000Z'::timestamptz
  ),
  (
    'dummy-image-05',
    'Chill Room Set — Full Collection',
    'dummy-chill-room-set-collection',
    'AI_IMAGE',
    NULL,
    NULL,
    'Lifestyle',
    '{}',
    'Three coordinated chill-room stills in one collection.',
    'A small lifestyle set: window light, desk corner, and sofa pose variants. Sold as a full collection for moodboard consistency.',
    ARRAY['lifestyle', 'collection', 'chill']::text[],
    'active',
    TRUE,
    TRUE,
    NULL,
    '{"thumbnail":"/media/categories/chill.jpg"}'::jsonb,
    'custom',
    'global',
    'optimized',
    '{"INR":{"regularPrice":2499,"currentPrice":1799},"USD":{"regularPrice":29.99,"currentPrice":21.99}}'::jsonb,
    '{"enabled":true,"label":"BEST VALUE BUNDLE","startDate":"2026-09-01T00:00:00.000Z","endDate":"2026-10-20T23:59:59.000Z"}'::jsonb,
    '{"mode":"demo","plays":"76800","playsNumeric":76800,"likes":"26K","likesNumeric":25600,"shares":"5K","sharesNumeric":5120,"engagementPct":8.2,"status":"trending","badge":"COLLECTION","insight":"Dummy AI image for storefront card review.","metricLabel":"VIEWS","engagementText":"26K likes · 5K shares","supportingText":"Creators are posting this format right now.","momentumLabel":"MOMENTUM IS CLIMBING ↑"}'::jsonb,
    '{"mode":"demo","addedThisWeek":18,"saved":124,"last24h":5,"activityLevel":"normal","note":"Dummy AI image seed."}'::jsonb,
    '{"enabled":true,"label":"FULL COLLECTION","headline":"Three coordinated chill-room stills in one collection.","supportingText":"","ctaText":"Get this image","microMessages":["Dummy seed"]}'::jsonb,
    '{"mode":"unlimited"}'::jsonb,
    '',
    '2048x2048',
    'PNG',
    'Instant access',
    '[{"id":"lic-personal","name":"Personal","description":"Social posts & personal projects","priceAdjustment":0},{"id":"lic-commercial","name":"Commercial","description":"Brand & client work","priceAdjustment":18}]'::jsonb,
    '[{"badge":"HIGH-RES PNG","title":"Print and post ready","description":"2048×2048 PNG with clean edges for social crops."},{"badge":"COMMERCIAL-SAFE","title":"Clear licensing tiers","description":"Personal and commercial options at checkout."},{"badge":"CHARACTER-READY","title":"Consistent look language","description":"Designed to pair with prompts and caption packs."}]'::jsonb,
    '{"dimensionsSupporting":"Square / vertical friendly","formatSupporting":"PNG or text unlock","accessSupporting":"Instant library access","usageMain":"Personal + social","usageSupporting":"Commercial upgrade available"}'::jsonb,
    64,
    115136,
    NULL,
    NULL,
    '{"resolution":"2048x2048","format":"PNG","fileSizeLabel":"2–3 MB each","images":[{"id":"dummy-image-05-1","url":"/media/categories/chill.jpg","previewUrl":"/media/categories/chill.jpg","fileName":"dummy-image-05-1.png","isCover":true,"sizeLabel":"2.4 MB"},{"id":"dummy-image-05-2","url":"/media/videos/drift-mode.jpg","previewUrl":"/media/videos/drift-mode.jpg","fileName":"dummy-image-05-2.png","isCover":false,"sizeLabel":"2.4 MB"},{"id":"dummy-image-05-3","url":"/media/videos/moon-groove.jpg","previewUrl":"/media/videos/moon-groove.jpg","fileName":"dummy-image-05-3.png","isCover":false,"sizeLabel":"2.4 MB"}],"collectionId":"dummy-col-chill-room","collectionName":"Chill Room Set","isCollectionPack":true,"collectionBundle":{"compareAtInr":2997,"compareAtUsd":38.97,"badgeText":"BEST VALUE"},"dealSettings":{"enableFullCollection":true,"enableAddMoreImages":false,"collectionBadgeText":"FULL SET","massiveCollectionThreshold":12}}'::jsonb,
    NULL,
    '2026-09-13T10:00:00.000Z'::timestamptz,
    '2026-09-13T10:00:00.000Z'::timestamptz
  ),
  (
    'dummy-image-06',
    'Hip-Hop Poster Frame',
    'dummy-hip-hop-poster-frame',
    'AI_IMAGE',
    NULL,
    NULL,
    'Poster',
    '{}',
    'Bold poster-style hip-hop character frame.',
    'High contrast and graphic shapes for flyer art, episode thumbnails, and streetwear drops.',
    ARRAY['hip-hop', 'poster', 'graphic']::text[],
    'active',
    FALSE,
    FALSE,
    NULL,
    '{"thumbnail":"/media/categories/hip-hop.jpg"}'::jsonb,
    'custom',
    'global',
    'optimized',
    '{"INR":{"regularPrice":999,"currentPrice":799},"USD":{"regularPrice":12.99,"currentPrice":9.99}}'::jsonb,
    '{"enabled":true,"label":"LIMITED INTRO PRICE","startDate":"2026-09-01T00:00:00.000Z","endDate":"2026-10-20T23:59:59.000Z"}'::jsonb,
    '{"mode":"demo","plays":"159600","playsNumeric":159600,"likes":"53K","likesNumeric":53200,"shares":"11K","sharesNumeric":10640,"engagementPct":8.2,"status":"normal","badge":"IMAGE","insight":"Dummy AI image for storefront card review.","metricLabel":"VIEWS","engagementText":"53K likes · 11K shares","supportingText":"Creators are posting this format right now.","momentumLabel":"MOMENTUM IS CLIMBING ↑"}'::jsonb,
    '{"mode":"demo","addedThisWeek":18,"saved":193,"last24h":5,"activityLevel":"normal","note":"Dummy AI image seed."}'::jsonb,
    '{"enabled":true,"label":"LIMITED INTRO PRICE","headline":"Bold poster-style hip-hop character frame.","supportingText":"","ctaText":"Get this image","microMessages":["Dummy seed"]}'::jsonb,
    '{"mode":"unlimited"}'::jsonb,
    '',
    '2048x2048',
    'PNG',
    'Instant access',
    '[{"id":"lic-personal","name":"Personal","description":"Social posts & personal projects","priceAdjustment":0},{"id":"lic-commercial","name":"Commercial","description":"Brand & client work","priceAdjustment":18}]'::jsonb,
    '[{"badge":"HIGH-RES PNG","title":"Print and post ready","description":"2048×2048 PNG with clean edges for social crops."},{"badge":"COMMERCIAL-SAFE","title":"Clear licensing tiers","description":"Personal and commercial options at checkout."},{"badge":"CHARACTER-READY","title":"Consistent look language","description":"Designed to pair with prompts and caption packs."}]'::jsonb,
    '{"dimensionsSupporting":"Square / vertical friendly","formatSupporting":"PNG or text unlock","accessSupporting":"Instant library access","usageMain":"Personal + social","usageSupporting":"Commercial upgrade available"}'::jsonb,
    133,
    106267,
    NULL,
    NULL,
    '{"resolution":"2048x2048","format":"PNG","fileSizeLabel":"2.4 MB","images":[{"id":"dummy-image-06-1","url":"/media/categories/hip-hop.jpg","previewUrl":"/media/categories/hip-hop.jpg","fileName":"dummy-image-06-1.png","isCover":true,"sizeLabel":"2.4 MB"}],"introTimerDays":14,"introTimerExtensionHours":4}'::jsonb,
    NULL,
    '2026-09-13T10:00:00.000Z'::timestamptz,
    '2026-09-13T10:00:00.000Z'::timestamptz
  ),
  (
    'dummy-prompt-01',
    'Soft Idol Character Prompt',
    'dummy-soft-idol-character-prompt',
    'PROMPT',
    NULL,
    NULL,
    'Character',
    '{}',
    'Generate consistent soft-idol characters across outfits.',
    'Generate consistent soft-idol characters across outfits. Full prompt, negatives, and settings unlock after purchase — preview shows a teaser only.',
    ARRAY['prompt', 'idol', 'soft']::text[],
    'active',
    TRUE,
    TRUE,
    NULL,
    '{"thumbnail":"/media/categories/cute-fun.jpg"}'::jsonb,
    NULL,
    NULL,
    NULL,
    '{"INR":{"regularPrice":699,"currentPrice":549},"USD":{"regularPrice":8.99,"currentPrice":6.99}}'::jsonb,
    '{"enabled":true,"label":"LIMITED LAUNCH PRICE","startDate":"2026-09-01T00:00:00.000Z","endDate":"2026-10-15T23:59:59.000Z"}'::jsonb,
    '{"mode":"demo","plays":"0","playsNumeric":0,"likes":"0","likesNumeric":0,"shares":"0","sharesNumeric":0,"engagementPct":0,"status":"normal","badge":"PROMPT","insight":"Dummy prompt product for PDP review.","metricLabel":"UNLOCKS","engagementText":"0 likes · 0 shares","supportingText":"Creators are posting this format right now.","momentumLabel":"MOMENTUM IS CLIMBING ↑"}'::jsonb,
    '{"mode":"demo","addedThisWeek":14,"saved":226,"last24h":3,"activityLevel":"normal","note":"Dummy prompt seed."}'::jsonb,
    '{"enabled":true,"label":"PROMPT DROP","headline":"Generate consistent soft-idol characters across outfits.","supportingText":"Unlock the full generation stack after checkout.","ctaText":"Unlock prompt","microMessages":["Dummy seed"]}'::jsonb,
    '{"mode":"unlimited"}'::jsonb,
    '',
    '',
    'TXT',
    'Instant unlock',
    '[{"id":"lic-personal","name":"Personal","description":"Social posts & personal projects","priceAdjustment":0},{"id":"lic-commercial","name":"Commercial","description":"Brand & client work","priceAdjustment":10}]'::jsonb,
    '[{"badge":"FULL PROMPT","title":"Copy-paste generation stack","description":"Main prompt, negatives, and settings notes unlock after purchase."},{"badge":"STYLE LOCKED","title":"Repeatable results","description":"Built for consistent characters across scenes."},{"badge":"INSTANT UNLOCK","title":"Use in any AI tool","description":"Works with Midjourney, Flux, SD, and similar tools."}]'::jsonb,
    '{"dimensionsSupporting":"Square / vertical friendly","formatSupporting":"PNG or text unlock","accessSupporting":"Instant library access","usageMain":"Personal + social","usageSupporting":"Commercial upgrade available"}'::jsonb,
    176,
    96624,
    '{"mainPrompt":"Soft idol character, pastel styling, big expressive eyes, silky hair strands, clean studio backdrop, consistent face geometry, fashion-forward casual outfits, gentle bloom lighting, ultra detailed","negativePrompt":"blurry, horror, watermark, extra fingers, lowres","generationSettings":"CFG 6 · Steps 30 · Aspect 3:4 · Style: illustration","modelNotes":"Works best with illustration / stylized checkpoints.","instructions":"Keep character identity locks when changing outfits.","publicTeaser":"Soft idol character, pastel styling, big expressive eyes…","canGenerate":"Idol portraits, outfit variants, pose sheets","sectionCount":3}'::jsonb,
    NULL,
    NULL,
    NULL,
    '2026-09-13T10:00:00.000Z'::timestamptz,
    '2026-09-13T10:00:00.000Z'::timestamptz
  ),
  (
    'dummy-prompt-02',
    'Street Reel Hook Prompt',
    'dummy-street-reel-hook-prompt',
    'PROMPT',
    NULL,
    NULL,
    'Reels',
    '{}',
    'Hook-frame prompt for punchy street reel stills.',
    'Hook-frame prompt for punchy street reel stills. Full prompt, negatives, and settings unlock after purchase — preview shows a teaser only.',
    ARRAY['prompt', 'reels', 'street']::text[],
    'active',
    TRUE,
    FALSE,
    NULL,
    '{"thumbnail":"/media/categories/viral-moves.jpg"}'::jsonb,
    NULL,
    NULL,
    NULL,
    '{"INR":{"regularPrice":649,"currentPrice":499},"USD":{"regularPrice":7.99,"currentPrice":5.99}}'::jsonb,
    '{"enabled":true,"label":"LIMITED LAUNCH PRICE","startDate":"2026-09-01T00:00:00.000Z","endDate":"2026-10-15T23:59:59.000Z"}'::jsonb,
    '{"mode":"demo","plays":"0","playsNumeric":0,"likes":"0","likesNumeric":0,"shares":"0","sharesNumeric":0,"engagementPct":0,"status":"normal","badge":"PROMPT","insight":"Dummy prompt product for PDP review.","metricLabel":"UNLOCKS","engagementText":"0 likes · 0 shares","supportingText":"Creators are posting this format right now.","momentumLabel":"MOMENTUM IS CLIMBING ↑"}'::jsonb,
    '{"mode":"demo","addedThisWeek":14,"saved":192,"last24h":3,"activityLevel":"normal","note":"Dummy prompt seed."}'::jsonb,
    '{"enabled":true,"label":"PROMPT DROP","headline":"Hook-frame prompt for punchy street reel stills.","supportingText":"Unlock the full generation stack after checkout.","ctaText":"Unlock prompt","microMessages":["Dummy seed"]}'::jsonb,
    '{"mode":"unlimited"}'::jsonb,
    '',
    '',
    'TXT',
    'Instant unlock',
    '[{"id":"lic-personal","name":"Personal","description":"Social posts & personal projects","priceAdjustment":0},{"id":"lic-commercial","name":"Commercial","description":"Brand & client work","priceAdjustment":10}]'::jsonb,
    '[{"badge":"FULL PROMPT","title":"Copy-paste generation stack","description":"Main prompt, negatives, and settings notes unlock after purchase."},{"badge":"STYLE LOCKED","title":"Repeatable results","description":"Built for consistent characters across scenes."},{"badge":"INSTANT UNLOCK","title":"Use in any AI tool","description":"Works with Midjourney, Flux, SD, and similar tools."}]'::jsonb,
    '{"dimensionsSupporting":"Square / vertical friendly","formatSupporting":"PNG or text unlock","accessSupporting":"Instant library access","usageMain":"Personal + social","usageSupporting":"Commercial upgrade available"}'::jsonb,
    142,
    70858,
    '{"mainPrompt":"Street reel hook frame, punchy silhouette, high contrast night lights, motion energy, phone-first 9:16 composition, strong facial reaction, social-first framing","negativePrompt":"dull colors, watermark, busy text, blurry","generationSettings":"CFG 5.5 · Steps 28 · Aspect 9:16","modelNotes":"Works best with illustration / stylized checkpoints.","instructions":"Keep character identity locks when changing outfits.","publicTeaser":"Street reel hook frame, punchy silhouette, high contrast…","canGenerate":"9:16 hook frames and reaction stills","sectionCount":3}'::jsonb,
    NULL,
    NULL,
    NULL,
    '2026-09-13T10:00:00.000Z'::timestamptz,
    '2026-09-13T10:00:00.000Z'::timestamptz
  ),
  (
    'dummy-prompt-03',
    'Pixar Snack Mascot Prompt',
    'dummy-pixar-snack-mascot-prompt',
    'PROMPT',
    NULL,
    NULL,
    'Food',
    '{}',
    'Turn snacks into lovable Pixar-like mascots.',
    'Turn snacks into lovable Pixar-like mascots. Full prompt, negatives, and settings unlock after purchase — preview shows a teaser only.',
    ARRAY['prompt', 'pixar', 'mascot']::text[],
    'active',
    FALSE,
    TRUE,
    NULL,
    '{"thumbnail":"/media/videos/mango-pop.jpg"}'::jsonb,
    NULL,
    NULL,
    NULL,
    '{"INR":{"regularPrice":749,"currentPrice":599},"USD":{"regularPrice":8.99,"currentPrice":6.99}}'::jsonb,
    '{"enabled":true,"label":"LIMITED LAUNCH PRICE","startDate":"2026-09-01T00:00:00.000Z","endDate":"2026-10-15T23:59:59.000Z"}'::jsonb,
    '{"mode":"demo","plays":"0","playsNumeric":0,"likes":"0","likesNumeric":0,"shares":"0","sharesNumeric":0,"engagementPct":0,"status":"normal","badge":"PROMPT","insight":"Dummy prompt product for PDP review.","metricLabel":"UNLOCKS","engagementText":"0 likes · 0 shares","supportingText":"Creators are posting this format right now.","momentumLabel":"MOMENTUM IS CLIMBING ↑"}'::jsonb,
    '{"mode":"demo","addedThisWeek":14,"saved":251,"last24h":3,"activityLevel":"normal","note":"Dummy prompt seed."}'::jsonb,
    '{"enabled":true,"label":"PROMPT DROP","headline":"Turn snacks into lovable Pixar-like mascots.","supportingText":"Unlock the full generation stack after checkout.","ctaText":"Unlock prompt","microMessages":["Dummy seed"]}'::jsonb,
    '{"mode":"unlimited"}'::jsonb,
    '',
    '',
    'TXT',
    'Instant unlock',
    '[{"id":"lic-personal","name":"Personal","description":"Social posts & personal projects","priceAdjustment":0},{"id":"lic-commercial","name":"Commercial","description":"Brand & client work","priceAdjustment":10}]'::jsonb,
    '[{"badge":"FULL PROMPT","title":"Copy-paste generation stack","description":"Main prompt, negatives, and settings notes unlock after purchase."},{"badge":"STYLE LOCKED","title":"Repeatable results","description":"Built for consistent characters across scenes."},{"badge":"INSTANT UNLOCK","title":"Use in any AI tool","description":"Works with Midjourney, Flux, SD, and similar tools."}]'::jsonb,
    '{"dimensionsSupporting":"Square / vertical friendly","formatSupporting":"PNG or text unlock","accessSupporting":"Instant library access","usageMain":"Personal + social","usageSupporting":"Commercial upgrade available"}'::jsonb,
    201,
    120399,
    '{"mainPrompt":"Pixar-style snack mascot, subsurface scattering, soft GI, charming personality, tiny limbs, glossy materials, cinematic three-point light, storybook appeal","negativePrompt":"scary, grotesque, logo text, flat lighting","generationSettings":"CFG 7 · Steps 32 · Aspect 1:1","modelNotes":"Works best with illustration / stylized checkpoints.","instructions":"Keep character identity locks when changing outfits.","publicTeaser":"Pixar-style snack mascot, subsurface scattering…","canGenerate":"Food mascots and packaging heroes","sectionCount":3}'::jsonb,
    NULL,
    NULL,
    NULL,
    '2026-09-13T10:00:00.000Z'::timestamptz,
    '2026-09-13T10:00:00.000Z'::timestamptz
  ),
  (
    'dummy-prompt-04',
    'Luxury Product Hero Prompt',
    'dummy-luxury-product-hero-prompt',
    'PROMPT',
    NULL,
    NULL,
    'Commercial',
    '{}',
    'Ad-ready product heroes with controlled speculars.',
    'Ad-ready product heroes with controlled speculars. Full prompt, negatives, and settings unlock after purchase — preview shows a teaser only.',
    ARRAY['prompt', 'product', 'luxury']::text[],
    'active',
    FALSE,
    FALSE,
    NULL,
    '{"thumbnail":"/media/videos/velvet-turn.jpg"}'::jsonb,
    NULL,
    NULL,
    NULL,
    '{"INR":{"regularPrice":899,"currentPrice":699},"USD":{"regularPrice":10.99,"currentPrice":8.49}}'::jsonb,
    '{"enabled":true,"label":"LIMITED LAUNCH PRICE","startDate":"2026-09-01T00:00:00.000Z","endDate":"2026-10-15T23:59:59.000Z"}'::jsonb,
    '{"mode":"demo","plays":"0","playsNumeric":0,"likes":"0","likesNumeric":0,"shares":"0","sharesNumeric":0,"engagementPct":0,"status":"normal","badge":"PROMPT","insight":"Dummy prompt product for PDP review.","metricLabel":"UNLOCKS","engagementText":"0 likes · 0 shares","supportingText":"Creators are posting this format right now.","momentumLabel":"MOMENTUM IS CLIMBING ↑"}'::jsonb,
    '{"mode":"demo","addedThisWeek":14,"saved":138,"last24h":3,"activityLevel":"normal","note":"Dummy prompt seed."}'::jsonb,
    '{"enabled":true,"label":"PROMPT DROP","headline":"Ad-ready product heroes with controlled speculars.","supportingText":"Unlock the full generation stack after checkout.","ctaText":"Unlock prompt","microMessages":["Dummy seed"]}'::jsonb,
    '{"mode":"unlimited"}'::jsonb,
    '',
    '',
    'TXT',
    'Instant unlock',
    '[{"id":"lic-personal","name":"Personal","description":"Social posts & personal projects","priceAdjustment":0},{"id":"lic-commercial","name":"Commercial","description":"Brand & client work","priceAdjustment":10}]'::jsonb,
    '[{"badge":"FULL PROMPT","title":"Copy-paste generation stack","description":"Main prompt, negatives, and settings notes unlock after purchase."},{"badge":"STYLE LOCKED","title":"Repeatable results","description":"Built for consistent characters across scenes."},{"badge":"INSTANT UNLOCK","title":"Use in any AI tool","description":"Works with Midjourney, Flux, SD, and similar tools."}]'::jsonb,
    '{"dimensionsSupporting":"Square / vertical friendly","formatSupporting":"PNG or text unlock","accessSupporting":"Instant library access","usageMain":"Personal + social","usageSupporting":"Commercial upgrade available"}'::jsonb,
    88,
    61512,
    '{"mainPrompt":"Luxury product hero, controlled specular highlights, shallow DOF, 85mm look, editorial grade, clean negative space for copy, premium materials","negativePrompt":"clutter, watermark, distorted product, harsh flash","generationSettings":"CFG 6 · Steps 30 · Aspect 4:5","modelNotes":"Works best with illustration / stylized checkpoints.","instructions":"Keep character identity locks when changing outfits.","publicTeaser":"Luxury product hero, controlled specular highlights…","canGenerate":"Ecommerce and campaign stills","sectionCount":3}'::jsonb,
    NULL,
    NULL,
    NULL,
    '2026-09-13T10:00:00.000Z'::timestamptz,
    '2026-09-13T10:00:00.000Z'::timestamptz
  ),
  (
    'dummy-prompt-05',
    'Comedy Object Prompt',
    'dummy-comedy-object-prompt',
    'PROMPT',
    NULL,
    NULL,
    'Comedy',
    '{}',
    'Give everyday objects ridiculous personalities.',
    'Give everyday objects ridiculous personalities. Full prompt, negatives, and settings unlock after purchase — preview shows a teaser only.',
    ARRAY['prompt', 'comedy', 'meme']::text[],
    'active',
    TRUE,
    FALSE,
    NULL,
    '{"thumbnail":"/media/categories/funny.jpg"}'::jsonb,
    NULL,
    NULL,
    NULL,
    '{"INR":{"regularPrice":549,"currentPrice":399},"USD":{"regularPrice":6.99,"currentPrice":4.99}}'::jsonb,
    '{"enabled":true,"label":"LIMITED LAUNCH PRICE","startDate":"2026-09-01T00:00:00.000Z","endDate":"2026-10-15T23:59:59.000Z"}'::jsonb,
    '{"mode":"demo","plays":"0","playsNumeric":0,"likes":"0","likesNumeric":0,"shares":"0","sharesNumeric":0,"engagementPct":0,"status":"normal","badge":"PROMPT","insight":"Dummy prompt product for PDP review.","metricLabel":"UNLOCKS","engagementText":"0 likes · 0 shares","supportingText":"Creators are posting this format right now.","momentumLabel":"MOMENTUM IS CLIMBING ↑"}'::jsonb,
    '{"mode":"demo","addedThisWeek":14,"saved":305,"last24h":3,"activityLevel":"normal","note":"Dummy prompt seed."}'::jsonb,
    '{"enabled":true,"label":"PROMPT DROP","headline":"Give everyday objects ridiculous personalities.","supportingText":"Unlock the full generation stack after checkout.","ctaText":"Unlock prompt","microMessages":["Dummy seed"]}'::jsonb,
    '{"mode":"unlimited"}'::jsonb,
    '',
    '',
    'TXT',
    'Instant unlock',
    '[{"id":"lic-personal","name":"Personal","description":"Social posts & personal projects","priceAdjustment":0},{"id":"lic-commercial","name":"Commercial","description":"Brand & client work","priceAdjustment":10}]'::jsonb,
    '[{"badge":"FULL PROMPT","title":"Copy-paste generation stack","description":"Main prompt, negatives, and settings notes unlock after purchase."},{"badge":"STYLE LOCKED","title":"Repeatable results","description":"Built for consistent characters across scenes."},{"badge":"INSTANT UNLOCK","title":"Use in any AI tool","description":"Works with Midjourney, Flux, SD, and similar tools."}]'::jsonb,
    '{"dimensionsSupporting":"Square / vertical friendly","formatSupporting":"PNG or text unlock","accessSupporting":"Instant library access","usageMain":"Personal + social","usageSupporting":"Commercial upgrade available"}'::jsonb,
    255,
    101745,
    '{"mainPrompt":"Funny object character, exaggerated facial expression, tiny sneakers, meme-ready pose, bright comic lighting, clean background, high readability at phone size","negativePrompt":"scary, NSFW, text overlays, blurry edges","generationSettings":"CFG 5 · Steps 26 · Aspect 1:1","modelNotes":"Works best with illustration / stylized checkpoints.","instructions":"Keep character identity locks when changing outfits.","publicTeaser":"Funny object character, exaggerated expression…","canGenerate":"Meme mascots and skit thumbnails","sectionCount":3}'::jsonb,
    NULL,
    NULL,
    NULL,
    '2026-09-13T10:00:00.000Z'::timestamptz,
    '2026-09-13T10:00:00.000Z'::timestamptz
  ),
  (
    'dummy-prompt-06',
    'Festival Fashion Prompt',
    'dummy-festival-fashion-prompt',
    'PROMPT',
    NULL,
    NULL,
    'Fashion',
    '{}',
    'Modern festival fashion looks with warm glow.',
    'Modern festival fashion looks with warm glow. Full prompt, negatives, and settings unlock after purchase — preview shows a teaser only.',
    ARRAY['prompt', 'fashion', 'festival']::text[],
    'active',
    FALSE,
    TRUE,
    NULL,
    '{"thumbnail":"/media/categories/bollywood.jpg"}'::jsonb,
    NULL,
    NULL,
    NULL,
    '{"INR":{"regularPrice":799,"currentPrice":649},"USD":{"regularPrice":9.99,"currentPrice":7.99}}'::jsonb,
    '{"enabled":true,"label":"LIMITED LAUNCH PRICE","startDate":"2026-09-01T00:00:00.000Z","endDate":"2026-10-15T23:59:59.000Z"}'::jsonb,
    '{"mode":"demo","plays":"0","playsNumeric":0,"likes":"0","likesNumeric":0,"shares":"0","sharesNumeric":0,"engagementPct":0,"status":"normal","badge":"PROMPT","insight":"Dummy prompt product for PDP review.","metricLabel":"UNLOCKS","engagementText":"0 likes · 0 shares","supportingText":"Creators are posting this format right now.","momentumLabel":"MOMENTUM IS CLIMBING ↑"}'::jsonb,
    '{"mode":"demo","addedThisWeek":14,"saved":169,"last24h":3,"activityLevel":"normal","note":"Dummy prompt seed."}'::jsonb,
    '{"enabled":true,"label":"PROMPT DROP","headline":"Modern festival fashion looks with warm glow.","supportingText":"Unlock the full generation stack after checkout.","ctaText":"Unlock prompt","microMessages":["Dummy seed"]}'::jsonb,
    '{"mode":"unlimited"}'::jsonb,
    '',
    '',
    'TXT',
    'Instant unlock',
    '[{"id":"lic-personal","name":"Personal","description":"Social posts & personal projects","priceAdjustment":0},{"id":"lic-commercial","name":"Commercial","description":"Brand & client work","priceAdjustment":10}]'::jsonb,
    '[{"badge":"FULL PROMPT","title":"Copy-paste generation stack","description":"Main prompt, negatives, and settings notes unlock after purchase."},{"badge":"STYLE LOCKED","title":"Repeatable results","description":"Built for consistent characters across scenes."},{"badge":"INSTANT UNLOCK","title":"Use in any AI tool","description":"Works with Midjourney, Flux, SD, and similar tools."}]'::jsonb,
    '{"dimensionsSupporting":"Square / vertical friendly","formatSupporting":"PNG or text unlock","accessSupporting":"Instant library access","usageMain":"Personal + social","usageSupporting":"Commercial upgrade available"}'::jsonb,
    119,
    77231,
    '{"mainPrompt":"Festival fashion character, contemporary ethnicwear cues, detailed fabric folds, warm festival lighting, elegant pose, editorial framing, soft bokeh","negativePrompt":"stereotype, low detail fabric, watermark, harsh shadows","generationSettings":"CFG 6.5 · Steps 30 · Aspect 3:4","modelNotes":"Works best with illustration / stylized checkpoints.","instructions":"Keep character identity locks when changing outfits.","publicTeaser":"Festival fashion character, detailed fabric folds…","canGenerate":"Fashion portraits and lookbook plates","sectionCount":3}'::jsonb,
    NULL,
    NULL,
    NULL,
    '2026-09-13T10:00:00.000Z'::timestamptz,
    '2026-09-13T10:00:00.000Z'::timestamptz
  ),
  (
    'dummy-caption-01',
    'Hook Lines for Night Reels',
    'dummy-hook-lines-night-reels',
    'CAPTION_PACK',
    NULL,
    NULL,
    'Hooks',
    '{}',
    '10 first-line hooks tuned for late-night posting.',
    '10 first-line hooks tuned for late-night posting. Preview shows sample style labels only — full captions and hashtags unlock after purchase.',
    ARRAY['captions', 'hooks', 'night']::text[],
    'active',
    TRUE,
    TRUE,
    NULL,
    '{"thumbnail":"/media/videos/moon-groove.jpg"}'::jsonb,
    NULL,
    NULL,
    NULL,
    '{"INR":{"regularPrice":349,"currentPrice":279},"USD":{"regularPrice":4.49,"currentPrice":3.49}}'::jsonb,
    '{"enabled":true,"label":"CREATOR WEEK","startDate":"2026-09-05T00:00:00.000Z","endDate":"2026-09-30T23:59:59.000Z"}'::jsonb,
    '{"mode":"demo","plays":"0","playsNumeric":0,"likes":"0","likesNumeric":0,"shares":"0","sharesNumeric":0,"engagementPct":0,"status":"trending","badge":"CAPTION PACK","insight":"Dummy caption pack for UI review.","metricLabel":"COPIES","engagementText":"0 likes · 0 shares","supportingText":"Creators are posting this format right now.","momentumLabel":"MOMENTUM IS CLIMBING ↑"}'::jsonb,
    '{"mode":"demo","addedThisWeek":22,"saved":324,"last24h":6,"activityLevel":"high","note":"Dummy caption pack seed."}'::jsonb,
    '{"enabled":true,"label":"CAPTION DROP","headline":"10 first-line hooks tuned for late-night posting.","supportingText":"Paired caption + hashtag items.","ctaText":"Get the pack","microMessages":["Dummy seed"]}'::jsonb,
    '{"mode":"unlimited"}'::jsonb,
    '',
    '',
    'TXT',
    'Instant unlock',
    '[{"id":"lic-personal","name":"Personal","description":"Social posts & personal projects","priceAdjustment":0},{"id":"lic-commercial","name":"Commercial","description":"Brand & client work","priceAdjustment":8}]'::jsonb,
    '[{"badge":"PAIRED SETS","title":"Caption + hashtags together","description":"Each item ships with a matching discovery tag set."},{"badge":"SCROLL-FIRST","title":"Written for retention","description":"Hooks, CTAs, and comment bait for short-form."},{"badge":"COPY READY","title":"No rewriting needed","description":"Paste into Instagram, TikTok, or YouTube Shorts."}]'::jsonb,
    '{"dimensionsSupporting":"Square / vertical friendly","formatSupporting":"PNG or text unlock","accessSupporting":"Instant library access","usageMain":"Personal + social","usageSupporting":"Commercial upgrade available"}'::jsonb,
    244,
    68076,
    NULL,
    '{"items":[{"id":"item-1","caption":"This hits different after midnight.","hashtags":["#nightreels","#fyp","#latepost","#vibes","#reels"],"label":"Hook","notes":""},{"id":"item-2","caption":"Don’t scroll — the drop is quiet on purpose.","hashtags":["#waitforit","#reels","#fyp","#creator","#mood"],"label":"Hook","notes":""},{"id":"item-3","caption":"POV: the city finally slows down.","hashtags":["#pov","#citylights","#reelsindia","#aesthetic","#fyp"],"label":"POV","notes":""},{"id":"item-4","caption":"Soft volume. Loud timing.","hashtags":["#chillreels","#timing","#creator","#viral","#fyp"],"label":"Flex","notes":""},{"id":"item-5","caption":"Save this for your 11pm post.","hashtags":["#savethis","#nightpost","#reels","#tips","#fyp"],"label":"CTA","notes":""},{"id":"item-6","caption":"If you felt that, you’re the target audience.","hashtags":["#relatable","#reels","#comments","#fyp","#viral"],"label":"Engagement","notes":""},{"id":"item-7","caption":"Loop once. Then pretend you meant to.","hashtags":["#loop","#funnyreels","#fyp","#reels","#creator"],"label":"Funny","notes":""},{"id":"item-8","caption":"This is your sign to post the chill cut.","hashtags":["#postit","#chill","#reels","#fyp","#content"],"label":"CTA","notes":""},{"id":"item-9","caption":"Low light. High retention.","hashtags":["#retention","#reelsgrowth","#fyp","#creator","#edit"],"label":"Hook","notes":""},{"id":"item-10","caption":"Tell me the timestamp that got you.","hashtags":["#comment","#reels","#engagement","#fyp","#viral"],"label":"Comment bait","notes":""}]}'::jsonb,
    NULL,
    NULL,
    '2026-09-13T10:00:00.000Z'::timestamptz,
    '2026-09-13T10:00:00.000Z'::timestamptz
  ),
  (
    'dummy-caption-02',
    'Twist Ending Captions',
    'dummy-twist-ending-captions',
    'CAPTION_PACK',
    NULL,
    NULL,
    'Curiosity',
    '{}',
    '8 curiosity captions built for delayed payoffs.',
    '8 curiosity captions built for delayed payoffs. Preview shows sample style labels only — full captions and hashtags unlock after purchase.',
    ARRAY['captions', 'twist', 'curiosity']::text[],
    'active',
    TRUE,
    FALSE,
    NULL,
    '{"thumbnail":"/media/videos/scroll-stopper.jpg"}'::jsonb,
    NULL,
    NULL,
    NULL,
    '{"INR":{"regularPrice":299,"currentPrice":249},"USD":{"regularPrice":3.99,"currentPrice":2.99}}'::jsonb,
    '{"enabled":true,"label":"CREATOR WEEK","startDate":"2026-09-05T00:00:00.000Z","endDate":"2026-09-30T23:59:59.000Z"}'::jsonb,
    '{"mode":"demo","plays":"0","playsNumeric":0,"likes":"0","likesNumeric":0,"shares":"0","sharesNumeric":0,"engagementPct":0,"status":"trending","badge":"CAPTION PACK","insight":"Dummy caption pack for UI review.","metricLabel":"COPIES","engagementText":"0 likes · 0 shares","supportingText":"Creators are posting this format right now.","momentumLabel":"MOMENTUM IS CLIMBING ↑"}'::jsonb,
    '{"mode":"demo","addedThisWeek":22,"saved":261,"last24h":6,"activityLevel":"high","note":"Dummy caption pack seed."}'::jsonb,
    '{"enabled":true,"label":"CAPTION DROP","headline":"8 curiosity captions built for delayed payoffs.","supportingText":"Paired caption + hashtag items.","ctaText":"Get the pack","microMessages":["Dummy seed"]}'::jsonb,
    '{"mode":"unlimited"}'::jsonb,
    '',
    '',
    'TXT',
    'Instant unlock',
    '[{"id":"lic-personal","name":"Personal","description":"Social posts & personal projects","priceAdjustment":0},{"id":"lic-commercial","name":"Commercial","description":"Brand & client work","priceAdjustment":8}]'::jsonb,
    '[{"badge":"PAIRED SETS","title":"Caption + hashtags together","description":"Each item ships with a matching discovery tag set."},{"badge":"SCROLL-FIRST","title":"Written for retention","description":"Hooks, CTAs, and comment bait for short-form."},{"badge":"COPY READY","title":"No rewriting needed","description":"Paste into Instagram, TikTok, or YouTube Shorts."}]'::jsonb,
    '{"dimensionsSupporting":"Square / vertical friendly","formatSupporting":"PNG or text unlock","accessSupporting":"Instant library access","usageMain":"Personal + social","usageSupporting":"Commercial upgrade available"}'::jsonb,
    181,
    45069,
    NULL,
    '{"items":[{"id":"item-1","caption":"Wait for the switch-up.","hashtags":["#plottwist","#reels","#fyp","#viral","#wait"],"label":"Twist","notes":""},{"id":"item-2","caption":"You thought this was going somewhere else.","hashtags":["#twist","#reels","#fyp","#funny","#viral"],"label":"Twist","notes":""},{"id":"item-3","caption":"Stay for the last two seconds.","hashtags":["#ending","#reels","#fyp","#creator","#viral"],"label":"Hook","notes":""},{"id":"item-4","caption":"Rewind. You blinked.","hashtags":["#rewind","#reels","#fyp","#detail","#viral"],"label":"CTA","notes":""},{"id":"item-5","caption":"Not the ending you expected.","hashtags":["#unexpected","#reels","#fyp","#story","#viral"],"label":"Twist","notes":""},{"id":"item-6","caption":"I set you up on purpose.","hashtags":["#setup","#funnyreels","#fyp","#reels","#viral"],"label":"Funny","notes":""},{"id":"item-7","caption":"Comment if you saw it coming.","hashtags":["#comment","#reels","#fyp","#quiz","#viral"],"label":"Comment bait","notes":""},{"id":"item-8","caption":"Second watch hits harder.","hashtags":["#rewatch","#reels","#fyp","#loop","#viral"],"label":"CTA","notes":""}]}'::jsonb,
    NULL,
    NULL,
    '2026-09-13T10:00:00.000Z'::timestamptz,
    '2026-09-13T10:00:00.000Z'::timestamptz
  ),
  (
    'dummy-caption-03',
    'Soft Launch Captions',
    'dummy-soft-launch-captions',
    'CAPTION_PACK',
    NULL,
    NULL,
    'Relationship',
    '{}',
    '9 soft-launch lines for couple and friendship posts.',
    '9 soft-launch lines for couple and friendship posts. Preview shows sample style labels only — full captions and hashtags unlock after purchase.',
    ARRAY['captions', 'relationship', 'soft-launch']::text[],
    'active',
    FALSE,
    TRUE,
    NULL,
    '{"thumbnail":"/media/videos/mirror-wave.jpg"}'::jsonb,
    NULL,
    NULL,
    NULL,
    '{"INR":{"regularPrice":329,"currentPrice":259},"USD":{"regularPrice":4.29,"currentPrice":3.19}}'::jsonb,
    '{"enabled":true,"label":"CREATOR WEEK","startDate":"2026-09-05T00:00:00.000Z","endDate":"2026-09-30T23:59:59.000Z"}'::jsonb,
    '{"mode":"demo","plays":"0","playsNumeric":0,"likes":"0","likesNumeric":0,"shares":"0","sharesNumeric":0,"engagementPct":0,"status":"normal","badge":"CAPTION PACK","insight":"Dummy caption pack for UI review.","metricLabel":"COPIES","engagementText":"0 likes · 0 shares","supportingText":"Creators are posting this format right now.","momentumLabel":"MOMENTUM IS CLIMBING ↑"}'::jsonb,
    '{"mode":"demo","addedThisWeek":22,"saved":236,"last24h":6,"activityLevel":"normal","note":"Dummy caption pack seed."}'::jsonb,
    '{"enabled":true,"label":"CAPTION DROP","headline":"9 soft-launch lines for couple and friendship posts.","supportingText":"Paired caption + hashtag items.","ctaText":"Get the pack","microMessages":["Dummy seed"]}'::jsonb,
    '{"mode":"unlimited"}'::jsonb,
    '',
    '',
    'TXT',
    'Instant unlock',
    '[{"id":"lic-personal","name":"Personal","description":"Social posts & personal projects","priceAdjustment":0},{"id":"lic-commercial","name":"Commercial","description":"Brand & client work","priceAdjustment":8}]'::jsonb,
    '[{"badge":"PAIRED SETS","title":"Caption + hashtags together","description":"Each item ships with a matching discovery tag set."},{"badge":"SCROLL-FIRST","title":"Written for retention","description":"Hooks, CTAs, and comment bait for short-form."},{"badge":"COPY READY","title":"No rewriting needed","description":"Paste into Instagram, TikTok, or YouTube Shorts."}]'::jsonb,
    '{"dimensionsSupporting":"Square / vertical friendly","formatSupporting":"PNG or text unlock","accessSupporting":"Instant library access","usageMain":"Personal + social","usageSupporting":"Commercial upgrade available"}'::jsonb,
    156,
    40404,
    NULL,
    '{"items":[{"id":"item-1","caption":"Not a soft launch. Just good lighting.","hashtags":["#softlaunch","#couple","#reels","#fyp","#love"],"label":"Soft launch","notes":""},{"id":"item-2","caption":"If you know, you know.","hashtags":["#ifyouknow","#reels","#fyp","#relationship","#vibes"],"label":"Mystery","notes":""},{"id":"item-3","caption":"Main character energy, supporting cast optional.","hashtags":["#maincharacter","#reels","#fyp","#funny","#love"],"label":"Funny","notes":""},{"id":"item-4","caption":"We make ordinary days look intentional.","hashtags":["#everydaylove","#reels","#fyp","#couplegoals","#vibes"],"label":"Romance","notes":""},{"id":"item-5","caption":"Tag the person who gets this without context.","hashtags":["#tagthem","#reels","#fyp","#friends","#viral"],"label":"Tag","notes":""},{"id":"item-6","caption":"Quietly putting this on the timeline.","hashtags":["#timeline","#reels","#fyp","#softlaunch","#love"],"label":"Soft launch","notes":""},{"id":"item-7","caption":"Proof that pacing is a love language.","hashtags":["#lovelanguage","#reels","#fyp","#couple","#vibes"],"label":"Romance","notes":""},{"id":"item-8","caption":"This one’s for the group chat historians.","hashtags":["#groupchat","#reels","#fyp","#funny","#friends"],"label":"Funny","notes":""},{"id":"item-9","caption":"Save for the day you finally post it.","hashtags":["#savethis","#reels","#fyp","#softlaunch","#later"],"label":"CTA","notes":""}]}'::jsonb,
    NULL,
    NULL,
    '2026-09-13T10:00:00.000Z'::timestamptz,
    '2026-09-13T10:00:00.000Z'::timestamptz
  ),
  (
    'dummy-caption-04',
    'Brand-Safe CTA Pack',
    'dummy-brand-safe-cta-pack',
    'CAPTION_PACK',
    NULL,
    NULL,
    'Brand',
    '{}',
    '7 polished CTAs for brand-safe creator posts.',
    '7 polished CTAs for brand-safe creator posts. Preview shows sample style labels only — full captions and hashtags unlock after purchase.',
    ARRAY['captions', 'cta', 'brand']::text[],
    'active',
    FALSE,
    FALSE,
    NULL,
    '{"thumbnail":"/media/videos/velvet-turn.jpg"}'::jsonb,
    NULL,
    NULL,
    NULL,
    '{"INR":{"regularPrice":399,"currentPrice":319},"USD":{"regularPrice":4.99,"currentPrice":3.99}}'::jsonb,
    '{"enabled":true,"label":"CREATOR WEEK","startDate":"2026-09-05T00:00:00.000Z","endDate":"2026-09-30T23:59:59.000Z"}'::jsonb,
    '{"mode":"demo","plays":"0","playsNumeric":0,"likes":"0","likesNumeric":0,"shares":"0","sharesNumeric":0,"engagementPct":0,"status":"normal","badge":"CAPTION PACK","insight":"Dummy caption pack for UI review.","metricLabel":"COPIES","engagementText":"0 likes · 0 shares","supportingText":"Creators are posting this format right now.","momentumLabel":"MOMENTUM IS CLIMBING ↑"}'::jsonb,
    '{"mode":"demo","addedThisWeek":22,"saved":182,"last24h":6,"activityLevel":"normal","note":"Dummy caption pack seed."}'::jsonb,
    '{"enabled":true,"label":"CAPTION DROP","headline":"7 polished CTAs for brand-safe creator posts.","supportingText":"Paired caption + hashtag items.","ctaText":"Get the pack","microMessages":["Dummy seed"]}'::jsonb,
    '{"mode":"unlimited"}'::jsonb,
    '',
    '',
    'TXT',
    'Instant unlock',
    '[{"id":"lic-personal","name":"Personal","description":"Social posts & personal projects","priceAdjustment":0},{"id":"lic-commercial","name":"Commercial","description":"Brand & client work","priceAdjustment":8}]'::jsonb,
    '[{"badge":"PAIRED SETS","title":"Caption + hashtags together","description":"Each item ships with a matching discovery tag set."},{"badge":"SCROLL-FIRST","title":"Written for retention","description":"Hooks, CTAs, and comment bait for short-form."},{"badge":"COPY READY","title":"No rewriting needed","description":"Paste into Instagram, TikTok, or YouTube Shorts."}]'::jsonb,
    '{"dimensionsSupporting":"Square / vertical friendly","formatSupporting":"PNG or text unlock","accessSupporting":"Instant library access","usageMain":"Personal + social","usageSupporting":"Commercial upgrade available"}'::jsonb,
    102,
    32538,
    NULL,
    '{"items":[{"id":"item-1","caption":"Shop the look — link in bio.","hashtags":["#brandpartner","#reels","#fyp","#shopthelook","#creator"],"label":"CTA","notes":""},{"id":"item-2","caption":"Made with [brand] energy.","hashtags":["#sponsored","#reels","#fyp","#branddeal","#ad"],"label":"Sponsored","notes":""},{"id":"item-3","caption":"Details that survive a second glance.","hashtags":["#product","#reels","#fyp","#details","#brand"],"label":"Product","notes":""},{"id":"item-4","caption":"Save this before your next shoot.","hashtags":["#creators","#reels","#fyp","#shootday","#tips"],"label":"CTA","notes":""},{"id":"item-5","caption":"Clean fit. Clear CTA.","hashtags":["#cleanaesthetic","#reels","#fyp","#brand","#style"],"label":"Flex","notes":""},{"id":"item-6","caption":"Comment “guide” for the checklist.","hashtags":["#guide","#reels","#fyp","#checklist","#creator"],"label":"Comment bait","notes":""},{"id":"item-7","caption":"Built for feeds that value craft.","hashtags":["#craft","#reels","#fyp","#brandstory","#quality"],"label":"Brand","notes":""}]}'::jsonb,
    NULL,
    NULL,
    '2026-09-13T10:00:00.000Z'::timestamptz,
    '2026-09-13T10:00:00.000Z'::timestamptz
  ),
  (
    'dummy-caption-05',
    'Desi Creator Caption Kit',
    'dummy-desi-creator-caption-kit',
    'CAPTION_PACK',
    NULL,
    NULL,
    'India',
    '{}',
    '10 bilingual-friendly lines for Indian creator feeds.',
    '10 bilingual-friendly lines for Indian creator feeds. Preview shows sample style labels only — full captions and hashtags unlock after purchase.',
    ARRAY['captions', 'india', 'desi']::text[],
    'active',
    TRUE,
    TRUE,
    NULL,
    '{"thumbnail":"/media/videos/saffron-swing.jpg"}'::jsonb,
    NULL,
    NULL,
    NULL,
    '{"INR":{"regularPrice":349,"currentPrice":269},"USD":{"regularPrice":4.49,"currentPrice":3.29}}'::jsonb,
    '{"enabled":true,"label":"CREATOR WEEK","startDate":"2026-09-05T00:00:00.000Z","endDate":"2026-09-30T23:59:59.000Z"}'::jsonb,
    '{"mode":"demo","plays":"0","playsNumeric":0,"likes":"0","likesNumeric":0,"shares":"0","sharesNumeric":0,"engagementPct":0,"status":"trending","badge":"CAPTION PACK","insight":"Dummy caption pack for UI review.","metricLabel":"COPIES","engagementText":"0 likes · 0 shares","supportingText":"Creators are posting this format right now.","momentumLabel":"MOMENTUM IS CLIMBING ↑"}'::jsonb,
    '{"mode":"demo","addedThisWeek":22,"saved":299,"last24h":6,"activityLevel":"high","note":"Dummy caption pack seed."}'::jsonb,
    '{"enabled":true,"label":"CAPTION DROP","headline":"10 bilingual-friendly lines for Indian creator feeds.","supportingText":"Paired caption + hashtag items.","ctaText":"Get the pack","microMessages":["Dummy seed"]}'::jsonb,
    '{"mode":"unlimited"}'::jsonb,
    '',
    '',
    'TXT',
    'Instant unlock',
    '[{"id":"lic-personal","name":"Personal","description":"Social posts & personal projects","priceAdjustment":0},{"id":"lic-commercial","name":"Commercial","description":"Brand & client work","priceAdjustment":8}]'::jsonb,
    '[{"badge":"PAIRED SETS","title":"Caption + hashtags together","description":"Each item ships with a matching discovery tag set."},{"badge":"SCROLL-FIRST","title":"Written for retention","description":"Hooks, CTAs, and comment bait for short-form."},{"badge":"COPY READY","title":"No rewriting needed","description":"Paste into Instagram, TikTok, or YouTube Shorts."}]'::jsonb,
    '{"dimensionsSupporting":"Square / vertical friendly","formatSupporting":"PNG or text unlock","accessSupporting":"Instant library access","usageMain":"Personal + social","usageSupporting":"Commercial upgrade available"}'::jsonb,
    219,
    58911,
    NULL,
    '{"items":[{"id":"item-1","caption":"Desi timing hits different.","hashtags":["#reelsindia","#desicreator","#fyp","#indianreels","#viral"],"label":"Hook","notes":""},{"id":"item-2","caption":"From the group chat to the grid.","hashtags":["#desivibes","#reels","#fyp","#india","#relatable"],"label":"Funny","notes":""},{"id":"item-3","caption":"Festival energy, weekday discipline.","hashtags":["#festival","#reelsindia","#fyp","#creator","#grind"],"label":"Flex","notes":""},{"id":"item-4","caption":"Mumbai traffic but make it aesthetic.","hashtags":["#mumbai","#reels","#fyp","#city","#aesthetic"],"label":"POV","notes":""},{"id":"item-5","caption":"Save this for your next family function reel.","hashtags":["#familyfunction","#reelsindia","#fyp","#desi","#save"],"label":"CTA","notes":""},{"id":"item-6","caption":"Comment your city if the beat found you.","hashtags":["#city","#reels","#fyp","#india","#comments"],"label":"Comment bait","notes":""},{"id":"item-7","caption":"Small creator, big drumroll.","hashtags":["#smallcreator","#reels","#fyp","#growth","#india"],"label":"Motivation","notes":""},{"id":"item-8","caption":"Outfit repeating? Beat is not.","hashtags":["#outfit","#reels","#fyp","#fashion","#desi"],"label":"Funny","notes":""},{"id":"item-9","caption":"This one is for the late posters.","hashtags":["#latepost","#reelsindia","#fyp","#night","#creator"],"label":"Hook","notes":""},{"id":"item-10","caption":"Tag your reel partner in crime.","hashtags":["#collab","#reels","#fyp","#friends","#desi"],"label":"Tag","notes":""}]}'::jsonb,
    NULL,
    NULL,
    '2026-09-13T10:00:00.000Z'::timestamptz,
    '2026-09-13T10:00:00.000Z'::timestamptz
  ),
  (
    'dummy-caption-06',
    'Fitness Form Captions',
    'dummy-fitness-form-captions',
    'CAPTION_PACK',
    NULL,
    NULL,
    'Fitness',
    '{}',
    '8 captions for form checks and training clips.',
    '8 captions for form checks and training clips. Preview shows sample style labels only — full captions and hashtags unlock after purchase.',
    ARRAY['captions', 'fitness', 'form']::text[],
    'active',
    FALSE,
    FALSE,
    NULL,
    '{"thumbnail":"/media/videos/beat-bounce.jpg"}'::jsonb,
    NULL,
    NULL,
    NULL,
    '{"INR":{"regularPrice":299,"currentPrice":239},"USD":{"regularPrice":3.99,"currentPrice":2.79}}'::jsonb,
    '{"enabled":true,"label":"CREATOR WEEK","startDate":"2026-09-05T00:00:00.000Z","endDate":"2026-09-30T23:59:59.000Z"}'::jsonb,
    '{"mode":"demo","plays":"0","playsNumeric":0,"likes":"0","likesNumeric":0,"shares":"0","sharesNumeric":0,"engagementPct":0,"status":"normal","badge":"CAPTION PACK","insight":"Dummy caption pack for UI review.","metricLabel":"COPIES","engagementText":"0 likes · 0 shares","supportingText":"Creators are posting this format right now.","momentumLabel":"MOMENTUM IS CLIMBING ↑"}'::jsonb,
    '{"mode":"demo","addedThisWeek":22,"saved":214,"last24h":6,"activityLevel":"normal","note":"Dummy caption pack seed."}'::jsonb,
    '{"enabled":true,"label":"CAPTION DROP","headline":"8 captions for form checks and training clips.","supportingText":"Paired caption + hashtag items.","ctaText":"Get the pack","microMessages":["Dummy seed"]}'::jsonb,
    '{"mode":"unlimited"}'::jsonb,
    '',
    '',
    'TXT',
    'Instant unlock',
    '[{"id":"lic-personal","name":"Personal","description":"Social posts & personal projects","priceAdjustment":0},{"id":"lic-commercial","name":"Commercial","description":"Brand & client work","priceAdjustment":8}]'::jsonb,
    '[{"badge":"PAIRED SETS","title":"Caption + hashtags together","description":"Each item ships with a matching discovery tag set."},{"badge":"SCROLL-FIRST","title":"Written for retention","description":"Hooks, CTAs, and comment bait for short-form."},{"badge":"COPY READY","title":"No rewriting needed","description":"Paste into Instagram, TikTok, or YouTube Shorts."}]'::jsonb,
    '{"dimensionsSupporting":"Square / vertical friendly","formatSupporting":"PNG or text unlock","accessSupporting":"Instant library access","usageMain":"Personal + social","usageSupporting":"Commercial upgrade available"}'::jsonb,
    134,
    32026,
    NULL,
    '{"items":[{"id":"item-1","caption":"Form first. Ego later.","hashtags":["#fitness","#formcheck","#reels","#fyp","#training"],"label":"Hook","notes":""},{"id":"item-2","caption":"Slow the rep. Feel the work.","hashtags":["#gymreels","#fitness","#fyp","#strength","#reels"],"label":"Cue","notes":""},{"id":"item-3","caption":"POV: your future PR is watching.","hashtags":["#pr","#fitnessmotivation","#fyp","#gym","#reels"],"label":"POV","notes":""},{"id":"item-4","caption":"Save this cue for leg day.","hashtags":["#legday","#fitness","#fyp","#savethis","#gym"],"label":"CTA","notes":""},{"id":"item-5","caption":"Clean reps > loud plates.","hashtags":["#cleantech","#fitness","#fyp","#strength","#reels"],"label":"Flex","notes":""},{"id":"item-6","caption":"Comment your weak point — no judgment.","hashtags":["#formhelp","#fitness","#fyp","#community","#gym"],"label":"Comment bait","notes":""},{"id":"item-7","caption":"Training log energy only.","hashtags":["#traininglog","#fitness","#fyp","#discipline","#reels"],"label":"Motivation","notes":""},{"id":"item-8","caption":"This is your reminder to brace.","hashtags":["#brace","#fitness","#fyp","#lifting","#reels"],"label":"Cue","notes":""}]}'::jsonb,
    NULL,
    NULL,
    '2026-09-13T10:00:00.000Z'::timestamptz,
    '2026-09-13T10:00:00.000Z'::timestamptz
  ),
  (
    'dummy-bundle-01',
    'Night Reel Kit',
    'dummy-night-reel-kit',
    'BUNDLE',
    NULL,
    NULL,
    'Bundles',
    '{}',
    'Midnight Footwork video + night hook captions.',
    'Ship a late-night reel faster: Midnight Footwork plus Hook Lines for Night Reels.',
    ARRAY['bundle', 'kit', 'dummy']::text[],
    'active',
    TRUE,
    TRUE,
    NULL,
    '{"thumbnail":"/media/videos/pulse-drop.jpg"}'::jsonb,
    'custom',
    NULL,
    NULL,
    '{"INR":{"regularPrice":1299,"currentPrice":899},"USD":{"regularPrice":15.99,"currentPrice":10.99}}'::jsonb,
    '{"enabled":true,"label":"BUNDLE SAVE","startDate":"2026-09-01T00:00:00.000Z","endDate":"2026-10-31T23:59:59.000Z"}'::jsonb,
    '{"mode":"demo","plays":"0","playsNumeric":0,"likes":"0","likesNumeric":0,"shares":"0","sharesNumeric":0,"engagementPct":0,"status":"trending","badge":"BUNDLE","insight":"Dummy bundle for kit PDP review.","metricLabel":"KITS","engagementText":"0 likes · 0 shares","supportingText":"Creators are posting this format right now.","momentumLabel":"MOMENTUM IS CLIMBING ↑"}'::jsonb,
    '{"mode":"demo","addedThisWeek":10,"saved":158,"last24h":2,"activityLevel":"normal","note":"Dummy bundle seed."}'::jsonb,
    '{"enabled":true,"label":"CREATOR KIT","headline":"Midnight Footwork video + night hook captions.","supportingText":"Priced below buying items separately.","ctaText":"Get the kit","microMessages":["Dummy seed","Save vs à la carte"]}'::jsonb,
    '{"mode":"unlimited"}'::jsonb,
    '',
    '',
    'KIT',
    'Instant unlock',
    '[{"id":"lic-personal","name":"Personal","description":"Social posts & personal projects","priceAdjustment":0},{"id":"lic-commercial","name":"Commercial","description":"Brand & client work","priceAdjustment":12}]'::jsonb,
    '[{"badge":"MULTI-ASSET","title":"Everything in one checkout","description":"Coordinated products priced below buying separately."},{"badge":"CREATOR KIT","title":"Ship a full post faster","description":"Video/image + copy + prompts where included."},{"badge":"BEST VALUE","title":"Savings vs à la carte","description":"Compare-at totals shown on the product page."}]'::jsonb,
    '{"dimensionsSupporting":"Square / vertical friendly","formatSupporting":"PNG or text unlock","accessSupporting":"Instant library access","usageMain":"Personal + social","usageSupporting":"Commercial upgrade available"}'::jsonb,
    118,
    106082,
    NULL,
    NULL,
    NULL,
    '{"includedProductIds":["dummy-video-01","dummy-caption-01"],"compareAtTotalInr":1078,"compareAtTotalUsd":13.48,"coverMode":"auto","coverAutoSource":"first","coverSlots":[]}'::jsonb,
    '2026-09-13T10:00:00.000Z'::timestamptz,
    '2026-09-13T10:00:00.000Z'::timestamptz
  ),
  (
    'dummy-bundle-02',
    'Character Launch Kit',
    'dummy-character-launch-kit',
    'BUNDLE',
    NULL,
    NULL,
    'Bundles',
    '{}',
    'Pastel portrait + soft idol prompt + soft-launch captions.',
    'Launch a character world with image, prompt, and soft-launch copy in one checkout.',
    ARRAY['bundle', 'kit', 'dummy']::text[],
    'active',
    FALSE,
    TRUE,
    NULL,
    '{"thumbnail":"/media/categories/cute-fun.jpg"}'::jsonb,
    'custom',
    NULL,
    NULL,
    '{"INR":{"regularPrice":1999,"currentPrice":1499},"USD":{"regularPrice":24.99,"currentPrice":17.99}}'::jsonb,
    '{"enabled":true,"label":"BUNDLE SAVE","startDate":"2026-09-01T00:00:00.000Z","endDate":"2026-10-31T23:59:59.000Z"}'::jsonb,
    '{"mode":"demo","plays":"0","playsNumeric":0,"likes":"0","likesNumeric":0,"shares":"0","sharesNumeric":0,"engagementPct":0,"status":"normal","badge":"BUNDLE","insight":"Dummy bundle for kit PDP review.","metricLabel":"KITS","engagementText":"0 likes · 0 shares","supportingText":"Creators are posting this format right now.","momentumLabel":"MOMENTUM IS CLIMBING ↑"}'::jsonb,
    '{"mode":"demo","addedThisWeek":10,"saved":116,"last24h":2,"activityLevel":"normal","note":"Dummy bundle seed."}'::jsonb,
    '{"enabled":true,"label":"CREATOR KIT","headline":"Pastel portrait + soft idol prompt + soft-launch captions.","supportingText":"Priced below buying items separately.","ctaText":"Get the kit","microMessages":["Dummy seed","Save vs à la carte"]}'::jsonb,
    '{"mode":"unlimited"}'::jsonb,
    '',
    '',
    'KIT',
    'Instant unlock',
    '[{"id":"lic-personal","name":"Personal","description":"Social posts & personal projects","priceAdjustment":0},{"id":"lic-commercial","name":"Commercial","description":"Brand & client work","priceAdjustment":12}]'::jsonb,
    '[{"badge":"MULTI-ASSET","title":"Everything in one checkout","description":"Coordinated products priced below buying separately."},{"badge":"CREATOR KIT","title":"Ship a full post faster","description":"Video/image + copy + prompts where included."},{"badge":"BEST VALUE","title":"Savings vs à la carte","description":"Compare-at totals shown on the product page."}]'::jsonb,
    '{"dimensionsSupporting":"Square / vertical friendly","formatSupporting":"PNG or text unlock","accessSupporting":"Instant library access","usageMain":"Personal + social","usageSupporting":"Commercial upgrade available"}'::jsonb,
    76,
    113924,
    NULL,
    NULL,
    NULL,
    '{"includedProductIds":["dummy-image-01","dummy-prompt-01","dummy-caption-03"],"compareAtTotalInr":1607,"compareAtTotalUsd":20.17,"coverMode":"auto","coverAutoSource":"first","coverSlots":[]}'::jsonb,
    '2026-09-13T10:00:00.000Z'::timestamptz,
    '2026-09-13T10:00:00.000Z'::timestamptz
  ),
  (
    'dummy-bundle-03',
    'Festival Creator Bundle',
    'dummy-festival-creator-bundle',
    'BUNDLE',
    NULL,
    NULL,
    'Bundles',
    '{}',
    'Saffron Spin-Out + festival fashion prompt + desi captions.',
    'Festive video energy with matching prompt and desi caption kit.',
    ARRAY['bundle', 'kit', 'dummy']::text[],
    'active',
    TRUE,
    FALSE,
    NULL,
    '{"thumbnail":"/media/videos/saffron-swing.jpg"}'::jsonb,
    'custom',
    NULL,
    NULL,
    '{"INR":{"regularPrice":2199,"currentPrice":1699},"USD":{"regularPrice":26.99,"currentPrice":19.99}}'::jsonb,
    '{"enabled":true,"label":"BUNDLE SAVE","startDate":"2026-09-01T00:00:00.000Z","endDate":"2026-10-31T23:59:59.000Z"}'::jsonb,
    '{"mode":"demo","plays":"0","playsNumeric":0,"likes":"0","likesNumeric":0,"shares":"0","sharesNumeric":0,"engagementPct":0,"status":"trending","badge":"BUNDLE","insight":"Dummy bundle for kit PDP review.","metricLabel":"KITS","engagementText":"0 likes · 0 shares","supportingText":"Creators are posting this format right now.","momentumLabel":"MOMENTUM IS CLIMBING ↑"}'::jsonb,
    '{"mode":"demo","addedThisWeek":10,"saved":101,"last24h":2,"activityLevel":"normal","note":"Dummy bundle seed."}'::jsonb,
    '{"enabled":true,"label":"CREATOR KIT","headline":"Saffron Spin-Out + festival fashion prompt + desi captions.","supportingText":"Priced below buying items separately.","ctaText":"Get the kit","microMessages":["Dummy seed","Save vs à la carte"]}'::jsonb,
    '{"mode":"unlimited"}'::jsonb,
    '',
    '',
    'KIT',
    'Instant unlock',
    '[{"id":"lic-personal","name":"Personal","description":"Social posts & personal projects","priceAdjustment":0},{"id":"lic-commercial","name":"Commercial","description":"Brand & client work","priceAdjustment":12}]'::jsonb,
    '[{"badge":"MULTI-ASSET","title":"Everything in one checkout","description":"Coordinated products priced below buying separately."},{"badge":"CREATOR KIT","title":"Ship a full post faster","description":"Video/image + copy + prompts where included."},{"badge":"BEST VALUE","title":"Savings vs à la carte","description":"Compare-at totals shown on the product page."}]'::jsonb,
    '{"dimensionsSupporting":"Square / vertical friendly","formatSupporting":"PNG or text unlock","accessSupporting":"Instant library access","usageMain":"Personal + social","usageSupporting":"Commercial upgrade available"}'::jsonb,
    61,
    103639,
    NULL,
    NULL,
    NULL,
    '{"includedProductIds":["dummy-video-02","dummy-prompt-06","dummy-caption-05"],"compareAtTotalInr":2347,"compareAtTotalUsd":27.97,"coverMode":"auto","coverAutoSource":"first","coverSlots":[]}'::jsonb,
    '2026-09-13T10:00:00.000Z'::timestamptz,
    '2026-09-13T10:00:00.000Z'::timestamptz
  ),
  (
    'dummy-bundle-04',
    'Comedy Clip Kit',
    'dummy-comedy-clip-kit',
    'BUNDLE',
    NULL,
    NULL,
    'Bundles',
    '{}',
    'Glitch Party Cut + comedy object prompt + twist captions.',
    'High-energy party video paired with comedy prompt and twist-ending captions.',
    ARRAY['bundle', 'kit', 'dummy']::text[],
    'active',
    TRUE,
    TRUE,
    NULL,
    '{"thumbnail":"/media/videos/glitch-party.jpg"}'::jsonb,
    'custom',
    NULL,
    NULL,
    '{"INR":{"regularPrice":1799,"currentPrice":1299},"USD":{"regularPrice":21.99,"currentPrice":15.99}}'::jsonb,
    '{"enabled":true,"label":"BUNDLE SAVE","startDate":"2026-09-01T00:00:00.000Z","endDate":"2026-10-31T23:59:59.000Z"}'::jsonb,
    '{"mode":"demo","plays":"0","playsNumeric":0,"likes":"0","likesNumeric":0,"shares":"0","sharesNumeric":0,"engagementPct":0,"status":"trending","badge":"BUNDLE","insight":"Dummy bundle for kit PDP review.","metricLabel":"KITS","engagementText":"0 likes · 0 shares","supportingText":"Creators are posting this format right now.","momentumLabel":"MOMENTUM IS CLIMBING ↑"}'::jsonb,
    '{"mode":"demo","addedThisWeek":10,"saved":134,"last24h":2,"activityLevel":"normal","note":"Dummy bundle seed."}'::jsonb,
    '{"enabled":true,"label":"CREATOR KIT","headline":"Glitch Party Cut + comedy object prompt + twist captions.","supportingText":"Priced below buying items separately.","ctaText":"Get the kit","microMessages":["Dummy seed","Save vs à la carte"]}'::jsonb,
    '{"mode":"unlimited"}'::jsonb,
    '',
    '',
    'KIT',
    'Instant unlock',
    '[{"id":"lic-personal","name":"Personal","description":"Social posts & personal projects","priceAdjustment":0},{"id":"lic-commercial","name":"Commercial","description":"Brand & client work","priceAdjustment":12}]'::jsonb,
    '[{"badge":"MULTI-ASSET","title":"Everything in one checkout","description":"Coordinated products priced below buying separately."},{"badge":"CREATOR KIT","title":"Ship a full post faster","description":"Video/image + copy + prompts where included."},{"badge":"BEST VALUE","title":"Savings vs à la carte","description":"Compare-at totals shown on the product page."}]'::jsonb,
    '{"dimensionsSupporting":"Square / vertical friendly","formatSupporting":"PNG or text unlock","accessSupporting":"Instant library access","usageMain":"Personal + social","usageSupporting":"Commercial upgrade available"}'::jsonb,
    94,
    122106,
    NULL,
    NULL,
    NULL,
    '{"includedProductIds":["dummy-video-04","dummy-prompt-05","dummy-caption-02"],"compareAtTotalInr":1797,"compareAtTotalUsd":21.47,"coverMode":"auto","coverAutoSource":"first","coverSlots":[]}'::jsonb,
    '2026-09-13T10:00:00.000Z'::timestamptz,
    '2026-09-13T10:00:00.000Z'::timestamptz
  ),
  (
    'dummy-bundle-05',
    'Brand Polish Bundle',
    'dummy-brand-polish-bundle',
    'BUNDLE',
    NULL,
    NULL,
    'Bundles',
    '{}',
    'Velvet Turn Editorial + luxury product prompt + brand CTAs.',
    'Premium editorial video with commercial prompt and brand-safe CTA pack.',
    ARRAY['bundle', 'kit', 'dummy']::text[],
    'active',
    FALSE,
    FALSE,
    NULL,
    '{"thumbnail":"/media/videos/velvet-turn.jpg"}'::jsonb,
    'custom',
    NULL,
    NULL,
    '{"INR":{"regularPrice":2499,"currentPrice":1999},"USD":{"regularPrice":29.99,"currentPrice":23.99}}'::jsonb,
    '{"enabled":true,"label":"BUNDLE SAVE","startDate":"2026-09-01T00:00:00.000Z","endDate":"2026-10-31T23:59:59.000Z"}'::jsonb,
    '{"mode":"demo","plays":"0","playsNumeric":0,"likes":"0","likesNumeric":0,"shares":"0","sharesNumeric":0,"engagementPct":0,"status":"normal","badge":"BUNDLE","insight":"Dummy bundle for kit PDP review.","metricLabel":"KITS","engagementText":"0 likes · 0 shares","supportingText":"Creators are posting this format right now.","momentumLabel":"MOMENTUM IS CLIMBING ↑"}'::jsonb,
    '{"mode":"demo","addedThisWeek":10,"saved":83,"last24h":2,"activityLevel":"normal","note":"Dummy bundle seed."}'::jsonb,
    '{"enabled":true,"label":"CREATOR KIT","headline":"Velvet Turn Editorial + luxury product prompt + brand CTAs.","supportingText":"Priced below buying items separately.","ctaText":"Get the kit","microMessages":["Dummy seed","Save vs à la carte"]}'::jsonb,
    '{"mode":"unlimited"}'::jsonb,
    '',
    '',
    'KIT',
    'Instant unlock',
    '[{"id":"lic-personal","name":"Personal","description":"Social posts & personal projects","priceAdjustment":0},{"id":"lic-commercial","name":"Commercial","description":"Brand & client work","priceAdjustment":12}]'::jsonb,
    '[{"badge":"MULTI-ASSET","title":"Everything in one checkout","description":"Coordinated products priced below buying separately."},{"badge":"CREATOR KIT","title":"Ship a full post faster","description":"Video/image + copy + prompts where included."},{"badge":"BEST VALUE","title":"Savings vs à la carte","description":"Compare-at totals shown on the product page."}]'::jsonb,
    '{"dimensionsSupporting":"Square / vertical friendly","formatSupporting":"PNG or text unlock","accessSupporting":"Instant library access","usageMain":"Personal + social","usageSupporting":"Commercial upgrade available"}'::jsonb,
    43,
    85957,
    NULL,
    NULL,
    NULL,
    '{"includedProductIds":["dummy-video-06","dummy-prompt-04","dummy-caption-04"],"compareAtTotalInr":2797,"compareAtTotalUsd":33.97,"coverMode":"auto","coverAutoSource":"first","coverSlots":[]}'::jsonb,
    '2026-09-13T10:00:00.000Z'::timestamptz,
    '2026-09-13T10:00:00.000Z'::timestamptz
  ),
  (
    'dummy-bundle-06',
    'Chill Room Creator Set',
    'dummy-chill-room-creator-set',
    'BUNDLE',
    NULL,
    NULL,
    'Bundles',
    '{}',
    'Chill Room image collection + chill video + lifestyle captions.',
    'Moodboard-ready stills, a quiet flex loop, and soft lifestyle caption energy.',
    ARRAY['bundle', 'kit', 'dummy']::text[],
    'active',
    FALSE,
    TRUE,
    NULL,
    '{"thumbnail":"/media/categories/chill.jpg"}'::jsonb,
    'custom',
    NULL,
    NULL,
    '{"INR":{"regularPrice":2699,"currentPrice":2099},"USD":{"regularPrice":32.99,"currentPrice":24.99}}'::jsonb,
    '{"enabled":true,"label":"BUNDLE SAVE","startDate":"2026-09-01T00:00:00.000Z","endDate":"2026-10-31T23:59:59.000Z"}'::jsonb,
    '{"mode":"demo","plays":"0","playsNumeric":0,"likes":"0","likesNumeric":0,"shares":"0","sharesNumeric":0,"engagementPct":0,"status":"normal","badge":"BUNDLE","insight":"Dummy bundle for kit PDP review.","metricLabel":"KITS","engagementText":"0 likes · 0 shares","supportingText":"Creators are posting this format right now.","momentumLabel":"MOMENTUM IS CLIMBING ↑"}'::jsonb,
    '{"mode":"demo","addedThisWeek":10,"saved":79,"last24h":2,"activityLevel":"normal","note":"Dummy bundle seed."}'::jsonb,
    '{"enabled":true,"label":"CREATOR KIT","headline":"Chill Room image collection + chill video + lifestyle captions.","supportingText":"Priced below buying items separately.","ctaText":"Get the kit","microMessages":["Dummy seed","Save vs à la carte"]}'::jsonb,
    '{"mode":"unlimited"}'::jsonb,
    '',
    '',
    'KIT',
    'Instant unlock',
    '[{"id":"lic-personal","name":"Personal","description":"Social posts & personal projects","priceAdjustment":0},{"id":"lic-commercial","name":"Commercial","description":"Brand & client work","priceAdjustment":12}]'::jsonb,
    '[{"badge":"MULTI-ASSET","title":"Everything in one checkout","description":"Coordinated products priced below buying separately."},{"badge":"CREATOR KIT","title":"Ship a full post faster","description":"Video/image + copy + prompts where included."},{"badge":"BEST VALUE","title":"Savings vs à la carte","description":"Compare-at totals shown on the product page."}]'::jsonb,
    '{"dimensionsSupporting":"Square / vertical friendly","formatSupporting":"PNG or text unlock","accessSupporting":"Instant library access","usageMain":"Personal + social","usageSupporting":"Commercial upgrade available"}'::jsonb,
    39,
    81861,
    NULL,
    NULL,
    NULL,
    '{"includedProductIds":["dummy-image-05","dummy-video-03","dummy-caption-03"],"compareAtTotalInr":2887,"compareAtTotalUsd":34.47,"coverMode":"auto","coverAutoSource":"first","coverSlots":[]}'::jsonb,
    '2026-09-13T10:00:00.000Z'::timestamptz,
    '2026-09-13T10:00:00.000Z'::timestamptz
  )
ON CONFLICT (id) DO NOTHING;

SELECT id, name, slug, product_type, status
FROM public.products
WHERE id LIKE 'dummy-%'
ORDER BY product_type, id;

COMMIT;
